### DISCUSSION TITLE
Guidance on How to Deploy To Kubernetes

### DISCUSSION THREAD

**Discussion by craigmiller160** [bubuntux/nordvpn#184] [General]
**Is your feature request related to a problem? Please describe.**

Not really a problem, just something that would benefit me.

**Describe the solution you'd like**

I have a whole Kubernetes cluster setup on my home machine and I would love to add this. However, my understanding of the networking involved in this setup is limited. I can't seem to get the nginx proxy to connect to qbittorrent while the VPN is setup. I can get everything to work following your docker-compose documentation, but I can either have qbittorrent connected to the VPN, or have it be reach-able via the nginx proxy. I can't seem to do both together.

**Describe alternatives you've considered**

I could just use docker-compose, but kubernetes is my preference. Just hoping for some guidance from you, if you have it.

**Additional context**

Here is my Kubernetes deployment config file. I also have configmaps and secrets, but they are just for setting environment variables.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nord-vpn-torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nord-vpn-torrent
  template:
    metadata:
      labels:
        app: nord-vpn-torrent
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - net.ipv4.conf.all.rp_filter=2
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: false
      containers:
        - name: nordvpn
          image: bubuntux/nordvpn
          envFrom:
            - configMapRef:
                name: nordvpn-config
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: nordvpn-password
                  key: password
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent
          envFrom:
            - configMapRef:
                name: qbittorrent-config
          volumeMounts:
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /config
              name: qbittorrent-config
          ports:
            - containerPort: 30007
      volumes:
        - name: qbittorrent-config
          hostPath:
            path: /opt/kubernetes/data/qbittorrent/config
        - name: qbittorrent-downloads
          hostPath:
            path: /opt/kubernetes/data/qbittorrent/downloads
---
apiVersion: v1
kind: Service
metadata:
  name: nord-vpn-torrent-service
spec:
  type: NodePort
  selector:
    app: nord-vpn-torrent
  ports:
    - port: 30007
      targetPort: 30007
      nodePort: 30007
      protocol: TCP
```

**Comment by tgallacher** [comment]
Is your nginx proxy also running inside a pod on the same cluster? 

If it is external, you might just have to whitelist your IP range. For example, if your local IP range is something like `192.168.1.0/24` then you just need to set the appropriate env var:

```yml
 - name: nordvpn
          image: bubuntux/nordvpn
          envFrom:
            - configMapRef:
                name: nordvpn-config    # <------ not sure what settings you have configured here
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: nordvpn-password
                  key: password
            - name: NETWORK
               value: 192.168.1.0/24
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
```

then you should be able to `curl http://<ip of you node>:30007`

If your nginx proxy is _inside_ the cluster you might need some additional config.

Hope this helps
