### DISCUSSION TITLE
[Question] Question about the readme with the Web Container

### DISCUSSION THREAD

**Discussion by julien-vu** [bubuntux/nordvpn#191] [General]
Hello,

I followed the readme for another container and it appears that my web one could not find the joal one

Here is my docker compose 
```
services:
  vpn:
    container_name: nordvpn
    restart: unless-stopped
    image: bubuntux/nordvpn:openvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
    devices:
      - /dev/net/tun            # Required
    environment:
      - USER=mail # Required
      - "PASS=pass"
      - CONNECT=Country

  joal-vpn:
    container_name: joal-vpn
    image: anthonyraymond/joal:latest
    restart: unless-stopped
    network_mode: service:vpn
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8000", "--joal.ui.path.prefix=XXXX", "--joal.ui.secret-token=XXXXX"]
    logging:
      options:
        max-size: "2m"
        max-file: "3"

  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:
      - vpn:joal-vpn
    depends_on:
      - joal-vpn
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
```

I would like to know if something is wrong with the readme cause the Web container could not find the joal-vpn on even with the links

The error I have in the nginx container "host not found in upstream "joal-vpn" "

Am I missing something ?
