### DISCUSSION TITLE
How to enable access from the outside?

### DISCUSSION THREAD

**Discussion by martijnmelchers** [bubuntux/nordvpn#210] [Q&A] [answered]
I'm using your image and the VPN connects correctly however it doesn't seem to port the qbittorent client to the outside. I want to be able to access my instance from `http://<my-ip>:8080`. It connects but it says it takes too long to connect. What am I doing wrong?
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=X     # Required
      - "PASS='X"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=0.0.0.0/0  # So it can be accessed within the local network
      - DEBUG=Trace
    ports:
      - 8080:8080
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
```

**Comment by martijnmelchers** [comment]
I solved it using a simple reverse NGINX proxy! Easier than the provided solution in the readme which broke qbittorrent when not running on port 80

**Reply by dr41d45** [reply]
Could you share the solution, it is actual for me also. Thanks.

**Comment by martijnmelchers** [comment, marked as answer]
As I said in my original reply I solved it. To use a simple nginx reverse proxy create a file called `nginx.conf` and put the following content in it:
```
events {
  worker_connections 1024;
}

http {
  server {
    listen 8080;
    location / {
       proxy_hide_header   Referer;
       proxy_hide_header   Origin;
       proxy_set_header    Referer                 '';
       proxy_set_header    Origin                  '';
       proxy_redirect      off;
       proxy_set_header    Host                    $host;
       proxy_set_header    X-Real-IP               $remote_addr;
       proxy_set_header    X-Forwarded-Host        $host:$server_port;
       proxy_set_header    X-Forwarded-Server      $host;
       proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
       proxy_pass_header   Set-Cookie;
       proxy_pass_header   P3P;
       proxy_buffering     off;
       proxy_pass http://vpn:8080;
    }
  }
}
```

Then in your `docker-compose.yml`  add a 'proxy' entry
```yml
version: "3.9"
services:
  proxy:
    container_name: proxy
    image: nginx
    links:
      - vpn:service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - torrent
      - vpn
...
```

Just run `docker-compose up -d` and the proxy should start! You can access your server on `http://<your-ip>:8080`

Your `docker-compose.yml` should look something like this:

```yml
version: "3.9"
services:
  proxy:
    container_name: proxy
    image: nginx
    links:
      - vpn:service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - torrent
      - vpn
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               
    environment:                
      - USER=~
      - "PASS=~"
      - CONNECT=~
      - TECHNOLOGY=NordLynx
      - NETWORK=0.0.0.0/0
  torrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - qbittorrent-config:/config
      - /jellyfin-files:/files
    depends_on:
      - vpn
    restart: unless-stopped
volumes:
  qbittorrent-config:
```
