### DISCUSSION TITLE
Port issues

### DISCUSSION THREAD

**Discussion by sylphrena0** [bubuntux/nordvpn#228] [Q&A]
I can't seem to access qbittorrent using this docker version of nordvpn. Everything seems to be running fine, but I cannot access the webui for qbittorrent:

```
---
version: "3"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=6080
    volumes: #volume mappings
      - /mnt/md0/qBittorrent/Config:/config
      - /mnt/md0/qBittorrent/Torrents:/downloads
      - /mnt/md0/qBittorrent/Hydra:/hydradownloads
      - /mnt/md0/Hydra:/hydrapickup
      - /mnt/md0/Emby-Media/Movies:/movies
      - /mnt/md0/Emby-Media/TV:/tvshows
    restart: unless-stopped
    depends_on:
      - vpn
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=<myemail>@gmail.com    # Required
      - "PASS=<myp@ass>"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=10.44.0.0/16  # So it can be accessed within the local network. My subnet.
      - PORTS=80;443;8096;8080;8989;7878;25565;25564;25566;22;9117;6568;7070;3306;6080 #ports I use elsewhere
    ports:
      - 6080:6080 #8080 is in use by another program
```
