### DISCUSSION TITLE
nordvpn container is blocking access to webui of other containers when connecting through it

### DISCUSSION THREAD

**Discussion by Elyg** [bubuntux/nordvpn#290] [Q&A] [answered]
Hello,

I have been trying to setup a vpn container that I can use to route my other containers' traffic. I am able to setup all the individual containers without any problems. However, once I setup the vpn and have it be the network for e.g. radarr, I am no longer able to access the webui.

Nordvpn connects successfully and I can see the vpn ips on both of my containers and they seem to have access to the internet as well, when I tried to ping google. 

It seems to be due to the nordvpn itself, as once I run "nordvpn disconnect" in my vpn container's console i am able to access the webui of radarr almost immediately. I have searched around and whitelisting the ips was the answer, but it did not work. I tried whitelisting via the console all the possible combinations (e.g.```nordvpn whitelist add subnet 10.0.0.72/24```) I could think of, but I could not figure it out

Any ideas what I could do to resolve this issue ? Or is a nordvpn linux application problem ?

Any help is greatly appreciated

That's how I access radarr webui: ```10.0.0.72:7878```
Here's my docker compose:
```
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN               
      - SYS_MODULE              
    environment:               
      - USER=xxx
      - 'PASS=xxx'
      - COUNTRY=Canada
      - TZ=America/Montreal
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.72/24   # host ip
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 7878:7878 #radarr default port
    restart: unless-stopped
    network_mode: bridge
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=997
      - PGID=100
      - TZ=America/Montreal
    volumes:
      - /srv/dev-disk-by-uuid-4E521E47521E33E5/Config/radarr:/config
      - /srv/dev-disk-by-uuid-4E521E47521E33E5/Media/Movies:/movies
      - /srv/dev-disk-by-uuid-4E521E47521E33E5/download:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
```
