### DISCUSSION TITLE
sleep: cannot read realtime clock: Operation not permitted

### DISCUSSION THREAD

**Discussion by powerstreamcoh** [bubuntux/nordvpn#296] [Q&A]
I've been running the container on a RPi 4 with no issues. I recently added it to my RPi 3 B+ (other than model difference, running same settings and software), using the same compose file. It runs but I constantly get "sleep: cannot read realtime clock: Operation not permitted" in the log. It appears to connect and I do get a different IP address. Don't know if it's related but the qBittorrent container errors when trying to download a file. 
  
I have tried running as privileged. That stopped the sleep messages, but then I'm unable to connect the other containers to the VPN. Get  a "chown /var/lib/docker/containers/ resolv.conf: operation not permitted" error
  
Any ideas?
  
Update: Figured out that it wasn't causing an issues with qBittorrent (stupid permission issues lol). 
So far haven't found anything other then running it in privilege mode. Along with any container that will connect to it. Would rather not do that.
  
```
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: NordVPN
    cap_add:
      - NET_ADMIN
    environment:
      - USER=
      - PASS=
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=
    ports:
      - 8080:8080 #qbittorent
      - 9117:9117 #jackett
      - 8989:8989 #sonarr
      - 7878:7878 #radarr
      - 8686:8686 #lidarr
      - 9696:9696 #prowlarr
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - vpn_network
``` 
  
Log file just before the sleep message.
``` 
mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT

raw:
-P PREROUTING ACCEPT
-P OUTPUT ACCEPT

IP tables for ipv6:

sleep: cannot read realtime clock: Operation not permitted
sleep: cannot read realtime clock: Operation not permitted
sleep: cannot read realtime clock: Operation not permitted
sleep: cannot read realtime clock: Operation not permitted
sleep: cannot read realtime clock: Operation not permitted
