### DISCUSSION TITLE
Am I exposing my ports correctly?

### DISCUSSION THREAD

**Discussion by fredrikscode** [bubuntux/nordvpn#314] [Q&A]
I have issues getting the rtorrent incoming port to passthrough externally and guessing I'm missing something. I run my stack free from any middleware with the rtorrent port forwarded to the correct macvlan IP. I know this works without the VPN container as I've tried it so it's not the port fowarding.

Internally I can access the GUI fine (8080).

Here's my stack:
```
version: "3.2"

services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=USERNAME     # Required
      - "PASS=PASSWORD"         # Required
      - CONNECT=Finland
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.0/24  # So it can be accessed within the local network
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    networks:
      macvlan:
        ipv4_address: 10.0.0.30
  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - "./data/geoip:/data"
    env_file:
      - "./geoip-updater.env"
    restart: always

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn

  rtorrent-logs:
    image: bash
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "./data/rtorrent/log:/log"
    restart: always

networks:
  macvlan:
    external: true
```

Would anyone mind pointing out what my eyes have failed to notice?
