### DISCUSSION TITLE
Username or password is not correct. Please try again.

### DISCUSSION THREAD

**Discussion by 4others** [bubuntux/nordvpn#386] [Q&A] [answered]
Hi!
I've been using image: `ghcr.io/bubuntux/nordvpn:v3.10.0-1-1` for quite a while now, but just today started observing weird behavior there.

It still rarely works, but initially (till 11:00:00 CEST roughly) produced an error: 
```
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
```

However it changed and produces this one now:
```
Username or password is not correct. Please try again
```

Both password and username are OK, last successful connection was established around 160m ago, before 3PM CEST.

Any suggestions how could I keep it running on this image or do I need to use the newest version instead? 

**Note**: the app I use runs in Kubernetes, so current https://github.com/bubuntux/nordlynx cannot solve the issue.

**Comment by gado4525** [comment]
Im having the same issue, I had multiple containers using "latest" of this image, everything was working fine until saturday. Today I wasn't able to ssh to the container, it was in a endless reboot. I deleted everything,even images, net interfaces and recompose. The checked on portainer logs and found this 
``
[services.d] starting services
[services.d] done.
A new version of NordVPN is available! Please update the application.
Logging in via ‘--legacy’, ‘--username’, and ‘--password’ flags is deprecated. Use ‘nordvpn login' or ‘nordvpn login --nordaccount’ to log in via browser. Alternatively, you can use ‘nordvpn login --token’ to log in with a generated token.
We couldn't log you in. Make sure your credentials are correct. If you have MFA enabled, log in using the 'nordvpn login' command.
Invalid Username or password.
[cmd] /bin/sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
``
Legacy login is not longer supported? So this container is officially dead now?

**Reply by 4others** [reply]
Oh, so it's the same with the latest one too? What is the sha of the image you're using?

**Comment by fuzzaldrin** [comment]
Had the same issue, it looks like Nord have changed the login/auth process. I tried generating a token in the Nord dashboard and using that with the TOKEN env var but that doesn't work either. Based on the Dockerfile it looks like it doesn't actually pass the TOKEN to the NordVPN client but this could be potentially fixed. I'll see if I can get it working.

**Reply by 4others** [reply]
I am able to connect with the newest image, i.e. `28b8e88d337a` (note that it's nordvpn), with the TOKEN specified. It is not possible to specify one for the version I use normally, as the client is too old I presume...

**Reply by fuzzaldrin** [reply]
I'm going to give this a try today: https://github.com/bubuntux/nordlynx

**Reply by jamiejones1997** [reply]
> I am able to connect with the newest image, i.e. `28b8e88d337a`, with the TOKEN specified. It is not possible to specify one for the version I use normally, as the client is too old I presume...


Is that using the NordLynx technology?

**Reply by 4others** [reply]
It says so, but unfortunately I made a mistake saying it can connect, it does not do it, even though the prompt says so.

**Reply by fuzzaldrin** [reply]
This works for me but did require a little faff and does require Wireguard to be installed on the host: https://github.com/bubuntux/nordlynx

**Reply by 4others** [reply]
Sounds great! Unfortunately I cannot afford that - need to have a module too, not only tools (https://www.wireguard.com/install/) :/

**Reply by jamiejones1997** [reply]
I've ended up just paying for surfshark instead and using this https://github.com/ilteoood/docker-surfshark

Worked without any issues, took a few mins to migrate my other containers over to use it but still less hassle than getting the nordlynx working with wiregaurd

**Comment by jarlbrak** [comment]
Spent a few days trying to get the new https://github.com/bubuntux/nordlynx working with my environment. I got the container itself to connect but none of the other docker containers can access it. Tried to go back to what worked before and now I stumble upon this issue... Very annoying. Any fixes?

**Reply by fuzzaldrin** [reply]
Did you map the ports of the other containers to the VPN container in the same way as you would have for the old container?

```
vpn:
  container_name: vpn
  image: ghcr.io/bubuntux/nordlynx:2023-04-01
  cap_add:
    - NET_ADMIN #required
  environment:
    - PRIVATE_KEY=[super-secret-key-here] #required
    - PERSISTENT_KEEP_ALIVE=30
    - NET_LOCAL=192.168.0.0/24
    - QUERY=filters\[country_id\]=227 #UK Servers 
    #- RECONNECT=15
    - TZ=Europe/London
  ports:
    - 9696:9696               # prowlarr
    - 9117:9117               # jackett
    - 6789:6789               # nzbget
    - 6881:6881               # rtorrent
    - 3001:3001               # flood
    - 9091:9091               # transmission
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
  ```
