### DISCUSSION TITLE
Invalid token error when starting docker container

### DISCUSSION THREAD

**Discussion by Raptor05** [bubuntux/nordvpn#448] [Q&A]
Hey folks,

I'm using portainer on a synology to run my containers. In portainer I created a stack to run the NordVPN container. At first, I tried to run it standalone, before adjusting the other containers to use the vpn.

This is my compose file:

```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: NordVPN
    network_mode: bridge
    environment:
      - TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - CONNECT=Germany
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
      - PUID=1026
      - PGID=100
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    ports:
      - 8080:8080
```

And this is my log:

```
[migrations] started
[migrations] no migrations found
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in manual mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in manual mode
Firewall is up, everything has to go through the vpn
Enabling connection to secure interface and docker network
No inet6 network
Enabling connection to network 192.168.1.0/24

───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
  - A new version of NordVPN is available! Please update the application.
    - It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Invalid token.
```

I don't know what the issue is. But I have a few doubts about my config:

1. For what are the ports here?
2. Is the network correct? Or do I need to change it to my routers network? (my router is using 192.168.178.1) I tried both, it's not changing the log output.

I appreciate any help.

P.S.: The token is 100% correct!
