### ISSUE TITLE
Error running qBittorrent and nordvpn 

### ISSUE THREAD

**Issue by larivierec** [bubuntux/nordvpn#101]
**Describe the bug**
Simple actually, I simply start the docker using just qBittorrent and the docker image and after a couple of seconds I get this 
According to other issues seems like a Go lang issue, maybe it should be tied to that issue.
error: 

```
nordlynx   | runtime: mlock of signal stack failed: 12
nordlynx   | runtime: increase the mlock limit (ulimit -l) or
nordlynx   | runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
```
**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
torrent:
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    depends_on:
      - vpn
    restart: unless-stopped

  vpn:
    container_name: nordlynx
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=OBFUSCATED
      - "PASS=OBFUSCATED"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    ports:
      - 8080:8080
    restart: unless-stopped
```

**Expected behavior**
I just receive an mlock error after running it, then it crashes and restarts but qBittorrent does not.

**Additional context**

`docker info`
```
Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 45
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.657GiB
 Name: docker-server
 ID: 3LPB:MECZ:532C:GB6Z:KFIP:QLDS:B352:OAPT:RJ6Z:ZTKZ:42YX:DCL5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: OBFUSCATED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
