### ISSUE TITLE
Can't get / specify server group by country

### ISSUE THREAD

**Issue by gabrielwhite** [bubuntux/nordvpn#105]
I am trying to connect to a server group in a specific country.

The instructions give the example of "us -g p2p"

It also suggest you can find out the all the groups using this command

`docker run --rm bubuntux/nordvpn sh -c "nordvpnd & sleep 1 && nordvpn groups"`

This spits out a bunch of errors:

```
-panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5259a8]

goroutine 100 [running]:
nordvpn/daemon.Rpc.Groups(0x750d74, 0x4, 0xd50000, 0xd14300, 0xd1e0f0, 0xd14340, 0xd3a190, 0x0, 0x0, 0x75fb20, ...)
	/builds/nordvpn/apps-source/linux-app/src/daemon/rpc_groups.go:18 +0x94
nordvpn/daemon/pb._Daemon_Groups_Handler(0x65aa20, 0xd3a1e0, 0x762580, 0xd485e0, 0x11ca360, 0x0, 0x762580, 0xd485e0, 0x11ce0c0, 0x5)
	/builds/nordvpn/apps-source/linux-app/src/daemon/pb/service.pb.go:986 +0x194
google.golang.org/grpc.(*Server).processUnaryRPC(0xd4e000, 0x764e80, 0x1943400, 0x119c090, 0xd167a0, 0xb58f30, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x490
google.golang.org/grpc.(*Server).handleStream(0xd4e000, 0x764e80, 0x1943400, 0x119c090, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xaa4
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x10d6430, 0xd4e000, 0x764e80, 0x1943400, 0x119c090)
	/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0x7c
transport is closing
```

Here is my docker-compose:

``` 
nordvpn: 
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices: 
      - /dev/net/tun
    environment: 
      - USER=xxxx
      - PASS=xxxx
      - CONNECT=Brazil
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.0/24
    image: "bubuntux/nordvpn:3.7.4"
    restart: unless-stopped
```

This works 

`      - CONNECT=Brazil`

This works

`      - CONNECT=p2p`

This doesn't work

`      - CONNECT="us -g p2p"`

How can I specify country + group in Docker Compose?

Thanks!
