### ISSUE TITLE
Nordlynx wont connect. Container stays in starting mode and cannot ping from within the container outside of the network

### ISSUE THREAD

**Issue by dad-cmyk** [bubuntux/nordvpn#117]
**Describe the bug**
Container stays in 'Starting' status and when pinging from the container to 8.8.8.8 i get a Operation not permitted error, I am however able to ping internally.
This problem only exists with NordLynx, if shifting to OpenVPN its smooth sailing. 

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=xxxxx    # Required
      - "PASS=xxxxx"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24 
    ports:
      - 8080:8080

  torrent:
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
```

**Logs**
Log flile attached

[log.txt](https://github.com/bubuntux/nordvpn/files/5541197/log.txt)

**Additional context**
Running docker on ubuntu server 20.
