### ISSUE TITLE
Docker secret support for PASS

### ISSUE THREAD

**Issue by schklom** [bubuntux/nordvpn#123]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to keep confidential information in an insecure fashion ^^

**Describe the solution you'd like**

I would like to be able to use a docker secret for at least the `PASS` environment variable.
I'd like an extra environment variable called `FILE_PASS` or something in that fashion, and feed it `/run/secrets/nordvpn_password`.
Using a secret only requires docker-compose v3+ (or maybe v3.1+, not sure), not Docker swarm. The `docker-compose.yml` would look like this

```
version: "3.8"

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: vpn
    restart: on-failure:2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    volumes:
      - ${DOCKERCONFIG}/nordvpn/resolv.conf:/etc/resolv.conf
    environment:
      - USER=${NORDVPN_USERNAME}   # Required
      - PASSFILE=/run/secrets/nordvpn_password
      - CONNECT=${NORDVPN_CONNECT}
      - TECHNOLOGY=NordLynx
      - TZ=${TZ}
      - GROUPID=${PGID}
      - CYBER_SEC=Enable
    ports:
      - 1234:5678

secrets:
  nordvpn_password:
    file: /secrets-path/nordvpn_password
```

**Describe alternatives you've considered**

**Additional context**
