### ISSUE TITLE
Some help understanding (and some odd behaviour) for the nginx portion (newbie question)

### ISSUE THREAD

**Issue by ryd04** [bubuntux/nordvpn#127]
**Is your feature request related to a problem? Please describe.**
Hi, 

I used the docker-compose with web-proxy method. The included qbittorrent worked. However, I have 2 questions:

1. Is this only useful for if you are outside your network? Or is it also useful for not having to use the port? E.g. http://host/[container] instead of host:[port] ? 

2. With the provided docker-compose code with the web proxy, when I change the reference below I still get qbitorrent, but the formatting seems off (font is small), logo is huge on Chrome and I cannot log in. If I remove the “/qbit” everything works again and I’m not sure why.

3. Regarding the ports, if should I not be able to change what host port redirects in? Or does it not work because this is a web proxy? I noticed when I changed it the ports: -80:80 below to -79:80 I cannot get in (I realized this is no longer an http port but that’s how I thought the ports worked).

The docker-compose as copied from the main page, highlighting what I am talking about:
(I’m not sure why 

> 
```
web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:                                                                                   
      - vpn:torrent                                                                          
    depends_on:                                                                              
      - torrent                                                                              
    tmpfs:                                                                                   
      - /run                                                                                 
      - /tmp                                                                                 
      - /var/cache/nginx                                                                     
    ports:                                                                                   
      - 80:80 (Question #3 refers to here)                                                                               
      - 443:443                                                                              
    command: -w "http://torrent:8080/;/qbit" (Question #2 referring to this)  
```
