### ISSUE TITLE
VPN-connected Docker container unable to access other containers

### ISSUE THREAD

**Issue by khanzf** [bubuntux/nordvpn#151]
I have an application container (app) connected to the internet via a VPN-container (vpn). While that connectivity works, the app container is now unable to connect to the database container (db).

Is there a way to have the `app` container connect to local containers (or any RFC1918 address) while simultaneously also connected through the `vpn`? I would simply add `db` to the same `network_mode` but the `db` very specifically needs to be accessible by another container not connected through the `vpn` (A second application that will read from `db`).

The VPN container is running `bubuntux/nordvpn` and my docker-compose.yml is as follows:
```
version: "3.9"

services:
  app:
    build: app/
    depends_on:
      - db
    network_mode: service:vpn
    depends_on:
      - vpn
  db:
    image: postgres:alpine
    restart: always
    network_mode: service:vpn
    environment:
      POSTGRES_USER: PASSWORD
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: PASSWORD
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=EMAIL@EMAIL.COM
      - "PASS=PASSWORD"
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

I have attempted to use `link`, as follows:
```
app:
   links:
      - db
```

However, I get a startup error, specifically that `container type network can't be used with links.`

To restate the question: How do I have a container connected to the internet through a VPN container (In this case bubuntux/nordvpn) that is also accessible by non-VPN connected containers?

Thank you!

**Comment by khanzf** [comment]
Offering this question on Stack Overflow with a bounty of 50 points :)
https://stackoverflow.com/questions/66279975/vpn-connected-docker-container-unable-to-access-other-containers

**Comment by khanzf** [comment]
Bump!

**Comment by j-piecuch** [comment]
When you use `network_mode: service:vpn` in `app`'s config, the `app` and `vpn` services appear to run in the same container network-wise (specifically, they are in the same network namespace). They share interfaces, routing rules, ports, etc. Notably, they also share `/etc/resolv.conf` and `/etc/hosts`. Since `links` just adds a relevant entry to `/etc/hosts`, you can link from `app` to `db` by (counter-intuitively) adding a `db` link to the `vpn` service.

Try the following config:
```
version: "3.9"

services:
  app:
    build: app/
    depends_on:
      - db
    network_mode: service:vpn
  db:
    image: postgres:alpine
    network_mode: bridge
    restart: always
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DB
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=EMAIL@EMAIL.com
      - "PASS=PASSWORD"
      - CONNECT=foo
      - TECHNOLOGY=NordLynx
    links:
      - db # <----- This makes `db` accessible to `app`
    ulimits:
      memlock:
        soft: -1
        hard: -1
```
