### ISSUE TITLE
IP leakage during startup

### ISSUE THREAD

**Issue by omeryagmurlu** [bubuntux/nordvpn#165]
**Describe the bug**
Using transmission and this container results in ip leakage, if both containers are started up simultaneously (as in the case with `docker-compose up -d`). Only after a subsequent restart of transmission vpn is used. 

**To Reproduce without docker CLI**
Here's a docker-compose file for reproduction (you may need to open transmission ports, I'm using nginx on host to proxy in there):
```
---
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - "USER=REDACTED"     # Required
      - "PASS=REDACTED"         # Required
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24
    ulimits:                    # Recommended for High bandwidth scenarios
      memlock:
        soft: -1
        hard: -1
    ports:
      - 19091:9091

  transmission:
    image: linuxserver/transmission
    network_mode: service:vpn
    volumes:
      - ./config:/config
    depends_on:
      - vpn
```

**Expected behavior**
I expect the container not to leak the ip address.

To reproduce:

1. Use the docker-compose.yml above and start the containers with `docker-compose up -d transmission`
2. visit ipleak.net, activate torrent address detection and add the magnet file to transmission
3. notice how the vpn ip address gets picked up
4. Without removing the torrent, do `docker-compose down` and `docker-compose up -d transmission`
5. notice how your public ip address gets reported instead of the vpn
