### ISSUE TITLE
Multiple docker-compose files

### ISSUE THREAD

**Issue by Tockra** [bubuntux/nordvpn#167]
Hi there,

is it possible to run the vpn client in one docker-compose file and using it from different docker-compose files?
The examples the repo provides aren't clear :/

T

**Comment by thibaltus** [comment]
Yeah you can do this, but this is more related with docker-compose documentation...
You can specify to docker-compose cli multiple yaml file where you describe all your service. This can be achieve with `-f` argurment. 
For example:
```
docker-compose up -f ./vpm.yml -f ./torrent.yml ..... 
```

**Comment by Tockra** [comment]
Yes thank you. But you misunderstood my question.

I want to start a docker container with this image with an docker compose file. For example:
```yml
version: "3.3"
services:
    vpn:
        image: bubuntux/nordvpn
        cap_add:
          - NET_ADMIN               # Required
          - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
        sysctls:
          - net.ipv4.conf.all.rp_filter=2
        devices:
          - /dev/net/tun            # Required
        environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
            - USER=LOGIN     # Required
            - "PASS=PW"         # Required
            - CONNECT=Germany
            - TECHNOLOGY=NordLynx
            - NETWORK=192.168.1.0/24
        ulimits:                    # Recommended for High bandwidth scenarios
            memlock:
                soft: -1
                hard: -1
        ports:
            - 8080:8080
        networks:
            - vpn_net
            - default

networks:
  vpn_net:
    external:
      name: vpn_net
```
This container should run the whole time.

And I want multiple different docker containers (created with different files), which can be started at any point of time.

For example:
```yml
version: "3.3"
services:
    backup_service:
        image: ssarioglu/myip
        networks:
            - vpn_net


networks:
  vpn_net:
    external:
        name: vpn_net
        
```

Spoiler:
This specific solution with this network doesn't work. The myip container shows my own IP address.


But there should be a possibility to use the vpn client as Router for multiple different docker containers, created with different docker-compose files !?

**Comment by thibaltus** [comment]
Hum ok i see what you want.
As you point it, the example you give do not work. It is because you cannot redirect a docker network trafic thought a container !
The only way to use this vpn container as gateway for other docker container is to link theses containers with the vpn. To do this you need to use `network_mode`.

For example, you have a single docker-compose stack for the vpn
```
version: "3.3"
services:
    vpn:
        **container_name: vpn**
        image: bubuntux/nordvpn
        cap_add:
          - NET_ADMIN               # Required
          - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
        sysctls:
          - net.ipv4.conf.all.rp_filter=2
        devices:
          - /dev/net/tun            # Required
        environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
            - USER=LOGIN     # Required
            - "PASS=PW"         # Required
            - CONNECT=Germany
            - TECHNOLOGY=NordLynx
            - NETWORK=192.168.1.0/24
        ulimits:                    # Recommended for High bandwidth scenarios
            memlock:
                soft: -1
                hard: -1
        ports:
            - 8080:8080
```

And then you can define another docker-compose stack with services than use the vpn as gateway:
```
version: "3.3"
services:
    service_behind_vpn:
        image: alpine
        network_mode: **container:vpn**
``` 

**Note**: you have to set `container_name` for the vpn service, because docker-compose automatically prefix container name
