### ISSUE TITLE
Not starting on macOS

### ISSUE THREAD

**Issue by MGoeppl** [bubuntux/nordvpn#181]
Hi, the container always returns
```
Waiting for the service to start
Whoops! Cannot reach System Daemon.
 * Restarting /usr/sbin/nordvpnd nordvpn
start-stop-daemon: warning: failed to kill 78: No such process
   ...done.
Waiting for the service to start
Whoops! Cannot reach System Daemon.
 * Restarting /usr/sbin/nordvpnd nordvpn
start-stop-daemon: warning: failed to kill 79: No such process
   ...done.
Waiting for the service to start
Whoops! Cannot reach System Daemon.
 * Restarting /usr/sbin/nordvpnd nordvpn
start-stop-daemon: warning: failed to kill 79: No such process
   ...done.
Waiting for the service to start
Whoops! Cannot reach System Daemon.
 * Restarting /usr/sbin/nordvpnd nordvpn
start-stop-daemon: warning: failed to kill 79: No such process
   ...done.
Waiting for the service to start
Whoops! Cannot reach System Daemon.
 * Restarting /usr/sbin/nordvpnd nordvpn
start-stop-daemon: warning: failed to kill 78: No such process
   ...done.
```

in the logs and keeps restarting on my Intel Mac mini. 

The docker-compose part of the nordvpn client:
```
  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: nordvpn
    environment:
      - USER=user
      - PASS=pass
      - CONNECT=UK
      - TECHNOLOGY=OpenVPN
      - NETWORK=10.0.0.0/20
    cap_add:
      - net_admin
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    ports:
      - 1935:1935
    restart: always
```

Using v3.9.1 for the container works. 
Docker & macOS 11 are up to date.
