### ISSUE TITLE
Latest update breaks: dial tcp: i/o timeout+ntp check failed

### ISSUE THREAD

**Issue by schklom** [bubuntux/nordvpn#183]
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
Since I updated this morning, the container fails to start.

**To Reproduce without docker CLI**
docker-compose.yml
```
version: '3'
services:
  vpn:
    image: bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro # Logs don't have the right timezone without this
    environment:
      - USER=${NORDVPN_USERNAME}
      - "PASS=${NORDVPN_PASSWORD}"
      - CONNECT=${NORDVPN_CONNECT}
      - TECHNOLOGY=NordLynx
      - DNS=8.8.8.8
      - DEBUG="on"
  ...
```

**Expected behavior**
It connects as before the update

**Logs**
Add DEBUG=on and copy the logs here (make sure to remove you user and password from the logs as well).
```
Creating vpn ... done
+ iptables -F
+ iptables -X
+ iptables -P INPUT DROP
+ iptables -P FORWARD DROP
+ iptables -P OUTPUT DROP
+ ip6tables -F
+ ip6tables -X
+ ip6tables -P INPUT DROP
+ ip6tables -P FORWARD DROP
+ ip6tables -P OUTPUT DROP
+ iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A INPUT -i lo -j ACCEPT
+ iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A FORWARD -i lo -j ACCEPT
+ iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A OUTPUT -o lo -j ACCEPT
+ iptables -A OUTPUT -o tap+ -j ACCEPT
+ iptables -A OUTPUT -o tun+ -j ACCEPT
+ iptables -A OUTPUT -o nordlynx+ -j ACCEPT
+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
+ iptables -t nat -A POSTROUTING -o nordlynx+ -j MASQUERADE
+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A INPUT -p icmp -j ACCEPT
+ ip6tables -A INPUT -i lo -j ACCEPT
+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A FORWARD -p icmp -j ACCEPT
+ ip6tables -A FORWARD -i lo -j ACCEPT
+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o tap+ -j ACCEPT
+ ip6tables -A OUTPUT -o tun+ -j ACCEPT
+ ip6tables -A OUTPUT -o nordlynx+ -j ACCEPT
+ ip6tables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
+ ip6tables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
+ ip6tables -t nat -A POSTROUTING -o nordlynx+ -j MASQUERADE
+ iptables -A OUTPUT -m owner --gid-owner nordvpn -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner nordvpn -j ACCEPT
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
+ docker_network=192.168.17.3/24
+ [[ -n 192.168.17.3/24 ]]
+ iptables -A INPUT -s 192.168.17.3/24 -j ACCEPT
+ iptables -A FORWARD -d 192.168.17.3/24 -j ACCEPT
+ iptables -A FORWARD -s 192.168.17.3/24 -j ACCEPT
+ iptables -A OUTPUT -d 192.168.17.3/24 -j ACCEPT
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
+ docker6_network=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ mkdir -p /dev/net
+ [[ -c /dev/net/tun ]]
+ mknod -m 0666 /dev/net/tun c 10 200
mknod: /dev/net/tun: Operation not permitted
+ service nordvpn stop
+ rm -rf /run/nordvpn/nordvpnd.sock
+ service nordvpn start
+ echo 'Waiting for the service to start'
+ attempt_counter=0
+ max_attempts=50
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
Waiting for the service to start
+ '[' 0 -eq 50 ']'
+ echo -n .
+ attempt_counter=1
+ sleep 0.1
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
+ '[' 1 -eq 50 ']'
+ echo -n .
+ attempt_counter=2
+ sleep 0.1
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
+ nordvpn logout
You are not logged in.
+ nordvpn login -u <REDACTED> -p <REDACTED>
+ [[ -n '' ]]
+ [[ -n 8.8.8.8 ]]
+ nordvpn set dns 8.8.8.8
DNS is set to '8.8.8.8' successfully.
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n NordLynx ]]
+ nordvpn set technology NordLynx
Technology is successfully set to 'NordLynx'.
+ [[ -n 192.168.17.3/24 ]]
+ nordvpn whitelist add subnet 192.168.17.3/24
Subnet 192.168.17.0/24 is whitelisted successfully.
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ nordvpn -version
NordVPN Version 3.9.4
+ nordvpn settings
Technology: NordLynx
Firewall: enabled
Kill Switch: disabled
CyberSec: disabled
Notify: disabled
Auto-connect: disabled
DNS: 8.8.8.8
Whitelisted subnets:
        192.168.17.0/24
+ nordvpn connect Switzerland -g p2p
Please enter your login details.
Stdin/Stdout should be terminal
+ cat /var/log/nordvpn/daemon.log
2021/05/18 18:22:34 [Info] Daemon has started
2021/05/18 18:22:34 Kill Switch set to: disabled
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:34 Auto-connect set to: disabled
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:34 DNS set to: disabled
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:34 CyberSec set to: disabled
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:34 Protocol set to: UDP
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:34 Technology set to: OpenVPN
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:22:39 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": dial tcp: i/o timeout
2021/05/18 18:22:39 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout
2021/05/18 18:22:44 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": dial tcp: i/o timeout
2021/05/18 18:22:44 Get "https://boi9osyg1uwtyafn.com/v1/servers/countries": dial tcp: i/o timeout
2021/05/18 18:22:49 Post "https://x9fnzrtl4x8pynsf.com/v1/users/tokens": dial tcp: i/o timeout
2021/05/18 18:22:49 Get "https://icpsuawn1zy5amys.com/v1/servers/countries": dial tcp: i/o timeout
2021/05/18 18:22:54 Post "https://2ohvff3e8v46kb8.info/v1/users/tokens": dial tcp: i/o timeout
2021/05/18 18:22:54 Get "https://4qlnp8csnrj5zla.me/v1/servers/countries": dial tcp: i/o timeout
2021/05/18 18:22:59 Post "https://q8uvnsgljgste3f.info/v1/users/tokens": dial tcp: i/o timeout
2021/05/18 18:22:59 Get "https://w569ut7zbkiqf5b.xyz/v1/servers/countries": dial tcp: i/o timeout
2021/05/18 18:23:19 [Error] logging in: ntp check failed
2021/05/18 18:23:19 DNS set to: enabled
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/05/18 18:23:19 Technology set to: NordLynx
NordVPN App Connection Settings:
Technology: OpenVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

+ exit 1
```

**Additional context**
I thought the problem could be related to the loss of
```
devices:
      - /dev/net/tun
```
and
```
cap_add:
      - SYS_MODULE
```
but adding them doesn't solve the issue.

Thinking it might be a DNS problem, I tried setting
```
DNS: 8.8.8.8
```
but it didn't help either.

Distribution+architecture
```
$ uname -srvmpio
Linux 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 unknown unknown GNU/Linux
```
Hardware: Raspberry Pi 4

It might be a problem from NordVPN themselves, reverting to 3.9.1 and 3.9.4 fails because the container can't connect to servers.

**Comment by davidrobertson** [comment]
I'm having this issue as well, it seems to have started after the latest update.  Restarting the container does not work.  The only solution I've found is to rebuild the docker container.

**Comment by schklom** [comment]
@davidrobertson Building the container yourself makes it work ?

**Comment by bradcornford** [comment]
I'm seeing the same issue, i've pinned my version to `v3.9.1` and that is working for now

**Comment by schklom** [comment]
> 
> 
> I'm seeing the same issue, i've pinned my container version to `v3.9.1` and that is working for now

Could you share your docker-compose nordvpn service ?
Using
```
image: bubuntux/nordvpn:v3.9.1
```
brings the error
```
[Error] logging in: bad request
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
```
Maybe my container specification is wrong

**Comment by moritzchow** [comment]
The one that works for me is ghcr.io/bubuntux/nordvpn:v3.9.1
Don't know if the 3.9.4-1's problem is related to the iptable - even though I set the DNS to make the error gone, My connection routed still not reaching any websites other than the local network's ones.

**Comment by bradcornford** [comment]
Sure, its as follows:

```
version: "3.4"

services:
  nordvpn:
    image: bubuntux/nordvpn:v3.9.1
    container_name: vpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - "/dev/net/tun -d"
    environment:
      - USER=xxx
      - PASS=xxx
      - CONNECT=uk -g p2p
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/22
      - TZ=Europe/London
      - DNS=1.1.1.1,1.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 51413:51413 # Transmission - P2P
      - 51413:51413/udp # Transmission - P2P
      - 9091:9091 # Transmission - WebUI
    privileged: true
    restart: unless-stopped
```

**Comment by bradcornford** [comment]
Have you run `docker login` ?

**Comment by schklom** [comment]
No, I never have. But it was working before.

I'm starting to think the difference is because your container has root access, whereas I am using Rootless Docker.

**Comment by bradcornford** [comment]
I'm tried the `latest` tag now, and it seems to be working when using the following:

```
version: "3.4"

services:
  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: vpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - USER=xxx
      - PASS=xxx
      - CONNECT=uk -g p2p
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/22
      - TZ=Europe/London
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 51413:51413 # Transmission - P2P
      - 51413:51413/udp # Transmission - P2P
      - 9091:9091 # Transmission - WebUI
    volumes:
      - /dev/rtc:/dev/rtc:ro
    restart: unless-stopped

```
