### ISSUE TITLE
Reconnecting every ~4.5 hours (v3.10.0-1)

### ISSUE THREAD

**Issue by lv10wizard** [bubuntux/nordvpn#204]
> **Describe the bug**

The container reconnects every ~4h 30m (sometimes immediately after `$RECONNECT` seconds).

`https://api.nordvpn.com/v1/helpers/ips/insights` (wrongly?) returns `"protected":false` after some time.

On my Windows machine connected to `United States #8867` via the NordVPN app, `curl https://api.nordvpn.com/v1/helpers/ips/insights` returns `"protected":false` even though
the [nordvpn](https://www.nordvpn.com) site says: `Your Status: Protected` at the top.

`curl ifconfig.me` returns `23.81.176.114` (the IP of `United States #8867` reported by the NordVPN app).

>**To Reproduce without docker CLI**

Run for >5h and check the logs for reconnections.

`docker-compose.yml`:
```
version: "3"

services:
    vpn:
        image: bubuntux/nordvpn:3.10.0-1
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE # For NordLynx (wireguard)
        sysctls:
            - net.ipv4.conf.all.rp_filter=2 # NordLynx
        devices:
            - /dev/net/tun
        environment:
            - USER=${NORD_USER} # From .env
            - PASS=${NORD_PASS} # ^^^^^^^^^
            - TECHNOLOGY=NordLynx
            - NETWORK=192.168.1.0/24
```

> **Expected behavior**

The container should automatically reconnect only if there is some connection issue, not on an interval.

> **Logs**

The `vpn` container has been up about 4 days.
`docker logs --tail=1000 vpn | grep 'Uptime:'`
```
 Uptime: 4 hours 25 minutes 51 seconds
 Uptime: 4 hours 20 minutes 57 seconds
 Uptime: 5 minutes
 Uptime: 5 minutes
 Uptime: 5 minutes 1 second
 Uptime: 4 hours 20 minutes 56 seconds
 Uptime: 5 minutes 1 second
 Uptime: 5 minutes 1 second
 Uptime: 4 hours 40 minutes 45 seconds
 Uptime: 4 hours 35 minutes 59 seconds
 Uptime: 4 hours 20 minutes 48 seconds
 Uptime: 4 hours 21 minutes 23 seconds
 Uptime: 5 minutes
 Uptime: 4 hours 21 minutes 7 seconds
 Uptime: 5 minutes 1 second
 Uptime: 5 minutes 2 seconds
 Uptime: 4 hours 41 minutes 3 seconds
 Uptime: 4 hours 41 minutes 7 seconds
 Uptime: 4 hours 23 minutes 57 seconds
 Uptime: 5 minutes 2 seconds
 Uptime: 4 hours 21 minutes 14 seconds
 Uptime: 4 hours 20 minutes 52 seconds
 Uptime: 5 minutes
 Uptime: 3 minutes 16 seconds
 Uptime: 4 hours 40 minutes 47 seconds
 Uptime: 4 hours 31 minutes 5 seconds
 Uptime: 5 minutes
 Uptime: 4 hours 20 minutes 43 seconds
 Uptime: 4 hours 21 minutes 8 seconds
 Uptime: 4 hours 30 minutes 54 seconds
 Uptime: 4 hours 40 minutes 49 seconds
 Uptime: 4 hours 41 minutes
 Uptime: 5 minutes 2 seconds
 Uptime: 5 minutes
 Uptime: 4 hours 22 minutes 54 seconds
```
