### ISSUE TITLE
Torrent Container will not start unless KillSwitch is disabled

### ISSUE THREAD

**Issue by gamerguyquote** [bubuntux/nordvpn#212]
**Describe the bug**
When attempting to stand up a Transmission container and route the network through nordvpn, the torrent container will not start unless I have the NordVPN Environement variable "KILLSWITCH=disabled"

**To Reproduce without docker CLI**
```
version: '3'
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/New_York
      - USER=xxxx@xxx.com
      - PASS=xxxxxx
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
        #  - KILLSWITCH=disabled
    ports:
      - 8080:8080
    restart: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    network_mode: service:nordvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=xxxxxx
      - PASS=xxxxxxxx
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - nordvpn
    restart: unless-stopped
```

**Expected behavior**
Transmission will start after the NordVPN container, and all traffic will be routed through NordVPN. Instead, docker-compose prints out the following error:
```
ERROR: for transmission  Cannot start service transmission: No such container: cbeffd76a35be03c939754377ef8445a4f7a083845629a5d710ec010b6ada140
ERROR: Encountered errors while bringing up the project.
```

**Logs**
Neither NordVPN nor Transmission give any logs as to what might be causing this issue.
