### ISSUE TITLE
Container doesnt reconnect after PC sleep?

### ISSUE THREAD

**Issue by onionhammer** [bubuntux/nordvpn#23]
I'm running this on a development laptop (macOS mojave) with docker-compose, and a separate service with `network_mode: service:vpn` works fine until I close the laptop and re-open it, or otherwise interrupt the physical network connection of the VPN, and then the separate service loses all connectivity, but the vpn service simply shows

```
Sat Mar  9 17:56:59 2019 /etc/openvpn/up.sh tun0 1500 1585 10.8.8.27 255.255.255.0 init
Sat Mar  9 17:56:59 2019 /sbin/ip route add 207.189.30.102/32 via 172.31.0.1
Sat Mar  9 17:56:59 2019 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
Sat Mar  9 17:56:59 2019 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
Sat Mar  9 17:56:59 2019 Initialization Sequence Completed
```

Usage

```yml

  testdocker:
    build: ./
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped

  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    env_file:
      - creds.env
    environment:
      - COUNTRY=United_States
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=America/Denver
    ports:
      - 8080:80
    restart: unless-stopped
```
