### ISSUE TITLE
NordVPN misconfiguring host network

### ISSUE THREAD

**Issue by gabrielwhite** [bubuntux/nordvpn#234]
**Describe the bug**

When I run NordVPN, I believe that it's misconfiguring the network of the host. I can't access other subnets on my home network from the host that's running the NordVPN docker image. I believe this problem appeared in the latest version of NordVPN as I have not seen this problem previously.

When I run ping from the command line of the host machine with NordVPN running I see this:

```
PING 192.168.100.1 (192.168.100.1) 56(84) bytes of data.
From 192.168.96.1 icmp_seq=1 Destination Host Unreachable
From 192.168.96.1 icmp_seq=2 Destination Host Unreachable
From 192.168.96.1 icmp_seq=3 Destination Host Unreachable
```

192.168.96.1 is the IP of the NordVPN docker.

I can ping other hosts on the same subnet as the host machine (10.0.0.x) but I cannot access any hosts on other subnets.

If I disable the NordVPN docker and reboot the host, I can ping hosts on other subnets without a problem.

**To Reproduce without docker CLI**

```
services:

  nordvpn: 
    container_name: nordvpn
    image: ghcr.io/bubuntux/nordvpn
    networks: 
      - vpn
    cap_add:
      - NET_ADMIN
    environment: 
      - USER=XXX
      - PASS=XXX
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.0/24
      - DNS=10.0.0.11,10.0.0.10
      - TZ=America/Santiago
    ports: 
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped

networks:

  vpn:
    name: vpn
    driver: bridge
```

**Expected behavior**

That I can access other subnets from the host machine.

**Additional context**

Armbian Buster on Odroid HC4.
