### ISSUE TITLE
COUNTRY Not Respected

### ISSUE THREAD

**Issue by emmercm** [bubuntux/nordvpn#24]
Given a `docker-compose.yml` of (per readme):

```yaml
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:2019.03.09
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=...
      - PASS=...
      - COUNRTY=United_States
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=America/Detroit
    ports:
      - 8080:8080
      - 6881:6881
    restart: unless-stopped
```

I get a Canadian config:

```
Staring firewall...
Adding network route 192.168.1.0/24...
Whitelisting api.nordvpn.com...
Selecting the best server...
Searching for group: legacy_p2p
Searching for technology: openvpn_udp
Best server : ca187.nordvpn.com
Using config file /vpn/ovpn/ca187.nordvpn.com.udp.ovpn...
Connecting ( --pull-filter ignore "ping-restart" --ping-exit 180 )... 
```
