### ISSUE TITLE
Docker container gets terminated after around 1 minute of being started

### ISSUE THREAD

**Issue by Instellate** [bubuntux/nordvpn#243]
My docker containers just gets terminated after 1 minute of it being on. This is only a problem for the VPN containers too. Cause they are the ones that gets terminated according to the legs
```
---
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=email     # Required
      - "PASS=password"         # Required
      - CONNECT=Sweden
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 8787:8787
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /home/user/qbc:/config
      - /home/user/qbc:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/user/.config/readarr:/config
      - /home/user/reader:/library #optional
      - /home/user/qbc:/downloads #optional
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
```
Nothing special with logs more then it saying "Terminated".
The only idea that could have made them get terminated is Fail2Ban. But I cant risk removing that package at the momente
