### ISSUE TITLE
Unable to run & connect using latest build in ARMv7

### ISSUE THREAD

**Issue by Sol-Illadan** [bubuntux/nordvpn#253]
**Describe the bug**
NoedVPN is failing to run succesfully in my Odroid HC1/Armbian instance. It keeps getting stuck at init.

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: "3.7"
services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/docker/config.json:/config.json
    command: --schedule "0 0 4 * * *" --cleanup
    environment:
      - TZ=${TZ}
  portainer:
    container_name: portainer    
    image: portainer/portainer-ce:latest
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/docker/portainer/data:/data
      - ${CONFIG_DIR}/docker/shared:/shared 
    environment:
      - TZ=${TZ}
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:arm32v7-latest
    network_mode: service:nordvpn
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIR}/docker/qbittorrent/config:/config
      - ${NAS_STAGING}/downloads/torrents/data:/downloads
    depends_on:
      - nordvpn
  nordvpn: 
    container_name: nordvpn 
    image: bubuntux/nordvpn:armv7hf-latest 
    restart: always 
    cap_add: 
      - NET_ADMIN 
    restart: unless-stopped 
    environment: # Review  https://github.com/bubuntux/nordvpn#environment-variables
      - USER=************** 
      - PASS=************** 
      - CONNECT=United_States 
      - TECHNOLOGY=NordLynx 
      - NETWORK=192.168.2.0/24
      - KILLSWITCH=true 
      - DNS=208.67.222.222,8.8.4.4 
      - TZ=${TZ} 
      - DEUG=trace
    ports: 
      - 8080:8080
```

**Expected behavior**
I expect the container to connect to NordVPN, along with able to access & run the qbittorrent container as well

**Logs**
```
-
  

-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

Technology is successfully set to 'NordLynx'.

DNS is set to '208.67.222.222, 8.8.4.4' successfully.

Subnet 172.19.0.0/16 is whitelisted successfully.

Subnet 192.168.2.0/24 is whitelisted successfully.


-
  

-
\2021/10/07 23:02:51 PRE_CONNECT system info:

App Version: 3.8.7

OS Info:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"

NAME="Debian GNU/Linux"

VERSION_ID="10"

VERSION="10 (buster)"

VERSION_CODENAME=buster
      

n

HOME_URL="https://www.debian.org/"

SUPPORT_URL="https://www.debian.org/support"

BUG_REPORT_URL="https://bugs.debian.org/"


System Info:Linux 8e17a2c880d5 5.4.142-odroidxu4 #21.08.1 SMP PREEMPT Wed Aug 25 19:56:03 UTC 2021 armv7l GNU/Linux



Routing Table:

default via 172.19.0.1 dev eth0 

172.19.0.0/16 dev eth0 proto kernel scope link src 172.19.0.4 

192.168.2.0/24 via 172.19.0.1 dev eth0 

      

:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 


IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -s 104.17.207.102/32 -i eth0 -j ACCEPT

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.19.0.0/16 -j ACCEPT

-A INPUT -s 192.168.2.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.19.0.0/16 -j ACCEPT

-A FORWARD -s 172.19.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.2.0/24 -j ACCEPT

-A FORWARD -s 192.168.2.0/24 -j ACCEPT

-A OUTPUT -d 104.17.207.102/32 -o eth0 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -m owner --gid-owner 104 -j ACCEPT

-A OUTPUT -d 172.19.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.2.0/24 -j ACCEPT


nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE


mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT


raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT

      

:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT




|
/
-
\
|
/
-
\
|
/2021/10/07 23:02:53 [Error] disabling IPv6: seting net.ipv6.conf.all.disable_ipv6 to 1: exit status 255: sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system



  

-
\
|2021/10/07 23:02:53 POST_CONNECT system info:

Routing Table:

default via 172.19.0.1 dev eth0 

172.19.0.0/16 dev eth0 proto kernel scope link src 172.19.0.4 

192.168.2.0/24 via 172.19.0.1 dev eth0 

      

:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 


IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.19.0.0/16 -j ACCEPT

-A INPUT -s 192.168.2.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.19.0.0/16 -j ACCEPT

-A FORWARD -s 172.19.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.2.0/24 -j ACCEPT

-A FORWARD -s 192.168.2.0/24 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -m owner --gid-owner 104 -j ACCEPT

-A OUTPUT -d 172.19.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.2.0/24 -j ACCEPT


nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE


mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT


raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT

      

:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT




  
Whoops! We couldn't connect you to 'United_States'. Please try again. If the problem persists, contact our customer support.

```

**Additional context**
OS - Armbian 21.08.2 Buster armv7l
Kernel - 5.4.142-odroidxu4
Device - Odroid HC1 (with sata HDD)

Docker version - 20.10.8, build 3967b7d
Docker Compose version - 1.29.2, build 5becea4c (linuxserver.io build for ARM)
