### ISSUE TITLE
Give containers that both use the VPN access to each other

### ISSUE THREAD

**Issue by DeX3** [bubuntux/nordvpn#26]
Hey,

thanks for this image - it works beautifully. I'm trying to achieve the following setup

1. A container `foo` using `network_mode: service:vpn` to access the internet
2. Another container `bar` also using `network_mode: service_vpn` to access the internet

So far, this works like a charm - however, now I'd like to make `foo` and `bar` able to connect to each other (e.g. so that `bar` can run `curl http://foo` and it would work), while still using the vpn for connections to the outside. Is this possible to do?

Here's a simple demo `docker-compose` (only need to fill in nordvpn username & password):

```yml
version: "2"

services:

  vpn:
    image: 'bubuntux/nordvpn'
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    ports:
      - 8080:80   # foo
    environment:
      USER: "XXXXX"
      PASS: "YYYYY"
      COUNTRY: "ch"
      CATEGORY: "P2P"
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      NETWORK: "192.168.0.0/24"
    restart: "unless-stopped"

  
  foo:
    image: 'nginx'
    network_mode: service:vpn

  bar:
    image: 'giantswarm/tiny-tools'
    network_mode: service:vpn
    command: "/bin/sh -c 'while sleep 1; do curl -sS http://foo/; done'"
```
