### ISSUE TITLE
How do I get the working container ff963812e7bb65... ?

### ISSUE THREAD

**Issue by grover77** [bubuntux/nordvpn#269]
I had set this up and it was working great. I tried an image pull, and it broke. :( I added a tag of `works` to the previous image, referenced that (image: bubuntux/nordvpn:works), and all was good. My best guess is this happened in February. Now my drive crashed, so I have access to the files, but docker is not running. I've tried pulling all the releases listed, but none have the working hash... The new copies don't work either. I know this is a bizarre request, but does anyone know how I can get this exact image, or copy from the old filesystem?

Thanks!
Grover

**Comment by grover77** [comment]
Here is my docker-compose.yaml:
```
version: "3.7"
services:

  vpn:
    image: bubuntux/nordvpn:works
    container_name: vpn
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=<redacted>
      - "PASS=<redacted>"
      - "CONNECT=us -g p2p"
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.122.0/24
    ulimits:                    # Recommended for High bandwidth scenarios
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9091:9091
      - 8080:8080
      - 80:80
      - 8000:8000
```
