### ISSUE TITLE
Client no longer connecting

### ISSUE THREAD

**Issue by danps1** [bubuntux/nordvpn#280]
**Describe the bug**
Since latest update, the client is failing to connect to VPN.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN                        
    environment:
      - TZ=Australia/Sydney
      - USER=*****
      - PASS=*****
      - CONNECT=Australia
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/16
```

**Expected behavior**

A successful connection

**Logs**
```
Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Couldn't connect to server

[services.d] done.

Password login is deprecated.

'nordvpn login --nordaccount' will become the default login method in the future.

You are already logged in.

Invalid Username or password.

[cmd] /bin/sh exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.
```
**Additional context**

I have not changed the password, and have double-checked the login details with a browser.
