### ISSUE TITLE
Whoops! /run/nordvpn/nordvpnd.sock not found

### ISSUE THREAD

**Issue by mlukewizard** [bubuntux/nordvpn#282]
Error when using the docker compose example in the readme. Run with `docker-compose up`. docker-compose.yml looks like:

```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user@email.com     # Required
      - "PASS=pas$word"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
```
      

I realise the error message says 'Invalid Username or password', but I can guarantee I have typed them in correctly. The error is in the line: "Whoops! /run/nordvpn/nordvpnd.sock not found". The same error is produced when running nordvpn status.

Any ideas why the container errors and I can't connect to nord?

Trace is:

```
Recreating qbitorrent-docker_vpn_1 ... done
Recreating qbitorrent-docker_torrent_1 ... done
Attaching to qbitorrent-docker_vpn_1, qbitorrent-docker_torrent_1
vpn_1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
vpn_1      | [s6-init] ensuring user provided files have correct perms...exited 0.
vpn_1      | [fix-attrs.d] applying ownership & permissions fixes...
vpn_1      | [fix-attrs.d] docker_utils: applying...
vpn_1      | [fix-attrs.d] docker_utils: exited 0.
torrent_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
vpn_1      | [fix-attrs.d] nord_utils: applying...
vpn_1      | [fix-attrs.d] nord_utils: exited 0.
vpn_1      | [fix-attrs.d] done.
vpn_1      | [cont-init.d] executing container initialization scripts...
vpn_1      | [cont-init.d] 00-firewall: executing...
vpn_1      | Firewall is up, everything has to go through the vpn
vpn_1      | [cont-init.d] 00-firewall: exited 0.
vpn_1      | [cont-init.d] 10-tun: executing...
vpn_1      | [cont-init.d] 10-tun: exited 0.
vpn_1      | [cont-init.d] 20-inet: executing...
vpn_1      | Enabling connection to secure interface and docker network
torrent_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
torrent_1  | [fix-attrs.d] applying ownership & permissions fixes...
torrent_1  | [fix-attrs.d] done.
torrent_1  | [cont-init.d] executing container initialization scripts...
torrent_1  | [cont-init.d] 01-envfile: executing...
torrent_1  | [cont-init.d] 01-envfile: exited 0.
torrent_1  | [cont-init.d] 10-adduser: executing...
torrent_1  | usermod: no changes
torrent_1  |
torrent_1  | -------------------------------------
torrent_1  |           _         ()
torrent_1  |          | |  ___   _    __
torrent_1  |          | | / __| | |  /  \
torrent_1  |          | | \__ \ | | | () |
torrent_1  |          |_| |___/ |_|  \__/
torrent_1  |
torrent_1  |
torrent_1  | Brought to you by linuxserver.io
torrent_1  | -------------------------------------
torrent_1  |
torrent_1  | To support LSIO projects visit:
torrent_1  | https://www.linuxserver.io/donate/
torrent_1  | -------------------------------------
torrent_1  | GID/UID
torrent_1  | -------------------------------------
torrent_1  |
torrent_1  | User uid:    911
torrent_1  | User gid:    911
torrent_1  | -------------------------------------
torrent_1  |
vpn_1      | [cont-init.d] 20-inet: exited 0.
vpn_1      | [cont-init.d] 20-inet6: executing...
torrent_1  | [cont-init.d] 10-adduser: exited 0.
vpn_1      | No inet6 network
vpn_1      | [cont-init.d] 20-inet6: exited 0.
torrent_1  | [cont-init.d] 30-config: executing...
vpn_1      | [cont-init.d] 30-route: executing...
torrent_1  | [cont-init.d] 30-config: exited 0.
vpn_1      | Enabling connection to network 192.168.1.0/24
torrent_1  | [cont-init.d] 90-custom-folders: executing...
vpn_1      | [cont-init.d] 30-route: exited 0.
torrent_1  | [cont-init.d] 90-custom-folders: exited 0.
vpn_1      | [cont-init.d] 30-route6: executing...
torrent_1  | [cont-init.d] 99-custom-scripts: executing...
vpn_1      | [cont-init.d] 30-route6: exited 0.
vpn_1      | [cont-init.d] 40-allowlist: executing...
vpn_1      | [cont-init.d] 40-allowlist: exited 0.
vpn_1      | [cont-init.d] done.
vpn_1      | [services.d] starting services
torrent_1  | [custom-init] no custom files found exiting...
torrent_1  | [cont-init.d] 99-custom-scripts: exited 0.
torrent_1  | [cont-init.d] done.
torrent_1  | [services.d] starting services
vpn_1      | 2021/11/14 23:58:50 [Info] Daemon has started
torrent_1  | [services.d] done.
vpn_1      | 2021/11/14 23:58:50 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:50 error on making client request: Head "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:50 cdn api: X-Accept-Before UNIX value is lower than current local time
vpn_1      | 2021/11/14 23:58:51 [Info] Daemon has started
vpn_1      | 2021/11/14 23:58:51 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:51 error on making client request: Head "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:51 cdn api: X-Accept-Before UNIX value is lower than current local time
vpn_1      | 2021/11/14 23:58:52 [Info] Daemon has started
vpn_1      | 2021/11/14 23:58:52 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:52 error on making client request: Head "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:52 cdn api: X-Accept-Before UNIX value is lower than current local time
vpn_1      | 2021/11/14 23:58:53 [Info] Daemon has started
vpn_1      | 2021/11/14 23:58:53 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:53 error on making client request: Head "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:53 cdn api: X-Accept-Before UNIX value is lower than current local time
vpn_1      | 2021/11/14 23:58:54 [Info] Daemon has started
vpn_1      | 2021/11/14 23:58:54 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": EOF
vpn_1      | 2021/11/14 23:58:54 cdn api: X-Accept-Before UNIX value is lower than current local time
vpn_1      | s6-svwait: fatal: timed out
Whoops! /run/nordvpn/nordvpnd.sock not found
vpn_1      | Invalid Username or password.
```
