### ISSUE TITLE
Using NETWORK=0.0.0.0/0 may lead to IP leakage during startup

### ISSUE THREAD

**Issue by grusssel** [bubuntux/nordvpn#288]
**Describe the bug**
When setting NETWORK=0.0.0.0/0 and restarting both containers (for example on reboot or docker-compose up after changing something), there is a short amount of time where the real IP gets leaked. This happened consistently every time. 

This issue came up on an older version (3.10) as well as the latest one.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3.3"
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      TECHNOLOGY: NordLynx
      USER: ****
      PASS: ****
      CONNECT: "--group p2p pl "
      NETWORK: 0.0.0.0/0
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8088
    volumes:
      - /opt/qbittorrent/config:/config
      - /data/Torrents/:/downloads
    restart: unless-stopped
    network_mode: "service:nordvpn"
    depends_on:
      - "nordvpn"
```

**Expected behavior**
No IP leakage

**Logs**
No relevant logs

**Additional context**
I am not sure if this is an issue with this image or with nordvpn, or even an issue at all or just expected behaviour, but a warning in the documentation would be good either way. I came across the NETWORK=0.0.0.0/0 as a proposed solution for other issues without a disclaimer that it may be a problem.
