### ISSUE TITLE
NordVPN NEW Login Mechanism Update turns down the connection

### ISSUE THREAD

**Issue by walmer26** [bubuntux/nordvpn#300]
Attached the logs.

I was talking to NordVPN and they mentioned me that I should use it as [nordvpn login --legacy] but I was reading this image documentation and there is not a setup for this.

Could you please include this fix or the ability of this image to use new NordVPN login mechanism?

Thank you for the work you do!

Regards.

[_nordvpn_vpn_1_logs.txt](https://github.com/bubuntux/nordvpn/files/7739966/_nordvpn_vpn_1_logs.txt)

**Comment by bubuntux** [comment]
--legacy was added

**Comment by walmer26** [comment]
I have deleted the image and redeploy pulling latest and keep the same. Also contacted NordVPN support and replaced user and password with their suggestion below and does not connect as well.

Am I doing something wrong? Attached the log file.

Kind regards.

![image](https://user-images.githubusercontent.com/47731751/146662950-23c531a0-abed-465f-8a50-eea80f13b1b0.png)
[_nordvpn_vpn_1_logs (2).txt](https://github.com/bubuntux/nordvpn/files/7740277/_nordvpn_vpn_1_logs.2.txt)

**Comment by Bosco911** [comment]
Same problem as walmer26. Can't connect anymore.

```
version: '3'
services:
  app:
    image: ghcr.io/bubuntux/nordvpn
    container_name: bubuntux
    restart: always
    cap_add:
    - NET_ADMIN
    environment:
    - TECHNOLOGY=NordLynx
    - USER=xxxxxx@xxxx.com 
    - PASS='xxx'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

```
```
2021/12/19 17:19:11 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": dial tcp: i/o timeout
Whoops! /run/nordvpn/nordvpnd.sock not found
Invalid Username or password.
[cmd] /bin/sh exited 1
```
