### ISSUE TITLE
Connection dies every few hours

### ISSUE THREAD

**Issue by dinovich** [bubuntux/nordvpn#308]
I've set up a container using the following:
```
version: "3.5"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    network_mode: bridge
    container_name: nordvpnwireguard
    cap_add:
      - NET_ADMIN    # Required
    devices:
      - /dev/net/tun
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=...
      - PASS=...
      - CONNECT=Canada
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24  # So it can be accessed within the local network
    ports:
      - 8900:8900
      - 6881:6881
      - 6881:6881/udp`
```

Another docker container has 'network_mode: service:vpn' configured.
Everything seems to work perfectly fine, but after 3-4 hours it stops working.

Logs shows repeated errors that look like that:
2022/01/19 16:46:06 error on making client request: Head "https://downloads.ltlxvxjjmvhn.me/configs/dns/cybersec.json": dial tcp: lookup downloads.ltlxvxjjmvhn.me on 103.86.99.100:53: write udp 172.17.0.7:39214->103.86.99.100:53: write: operation not permitted
2022/01/19 16:46:06 rotating: transport rotator: can't find gateway

Restarting the containers (both the VPN and the other container that uses it), seems to work. But again, after a few hours, the same thing happens.

Any ideas how to solve this issue?

Thank you!
