### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by danieleperera** [bubuntux/nordvpn#320]
**Describe the bug**
Logs says it's connected to NordVPN but I'm having issue to navigate using the VPN.
I'm using the below docker-compose file to run the container.
```
services:
  vpn:
    container_name: vpn
    image: ghcr.io/bubuntux/nordvpn:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - USER=${USERNAME}
      - PASS=${PASSWORD}
      - TECHNOLOGY=NordLynx
      - CYBER_SEC=Enable
      - DNS=1.1.1.1,8.8.8.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    restart: always
```
Logs:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-tun: executing...
[cont-init.d] 10-tun: exited 0.
[cont-init.d] 20-inet: executing...
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing...
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing...
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing...
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing...
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
DNS is set to '1.1.1.1, 8.8.8.8' successfully.
Disabling DNS.
CyberSec is set to 'enabled' successfully.
Technology is successfully set to 'NORDLYNX'.
Subnet 172.18.0.0/16 is whitelisted successfully.
Connecting...
Connecting to REDACTED!
You are connected to REDACTED!
############################################################
__  .___  ___. .______     ______   .______     .___________.    ___      .__   __. .___________.
|  | |   \/   | |   _  \   /  __  \  |   _  \    |           |   /   \     |  \ |  | |           |
|  | |  \  /  | |  |_)  | |  |  |  | |  |_)  |   `---|  |----`  /  ^  \    |   \|  | `---|  |----`
|  | |  |\/|  | |   ___/  |  |  |  | |      /        |  |      /  /_\  \   |  . `  |     |  |
|  | |  |  |  | |  |      |  `--'  | |  |\  \----.   |  |     /  _____  \  |  |\   |     |  |
|__| |__|  |__| | _|       \______/  | _| `._____|   |__|    /__/     \__\ |__| \__|     |__|
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Please migrate to the NordLynx container (https://github.com/bubuntux/nordlynx)
Here is your private Key: REDACTED!
IP: 10.5.0.2/32
############################################################
Unstable connection detected!
Status: Connected
Current server:  REDACTED!
Country:  REDACTED!
City:  REDACTED!
Server IP: REDACTED!
Current technology: NORDLYNX
Current protocol: UDP
Transfer: 1.62 KiB received, 25.07 KiB sent
Uptime: 5 minutes 20 seconds
```

**Expected behavior**
To test if everything is working I usually run the below command:
`docker exec -it vpn curl https://ifconfig.co -vvv`

It's giving me this error:
```
* Rebuilt URL to: ifconfig.co/
* Could not resolve host: ifconfig.co
* Closing connection 0
curl: (6) Could not resolve host: ifconfig.co
```

I tried to set and unset DNS, but it doesn't seem to work.
I set up another docker container to use this container's network but the results are the same.

**Additional context**
Docker version 20.10.12
Running on Ubuntu 20.04.3 LTS
Running latest version of ghcr.io/bubuntux/nordvpn:latest

**Comment by bubuntux** [comment]
now you have the private key just move to nordlynx

**Comment by imthenachoman** [comment]
> now you have the private key just move to nordlynx

Can you please elaborate on what that means?

**Comment by bubuntux** [comment]
@imthenachoman you can read the console message,  https://github.com/bubuntux/nordlynx

**Comment by imthenachoman** [comment]
I got it figured it out. Thanks!

**Comment by WINOFFRG** [comment]
I am literally facing same issue again and again with both the repo's **nordvpn** and **nordlynx** where container faces DNS issue. 
```
root@2a18d44316e5:/# curl https://google.com
curl: (6) Could not resolve host: google.com
```
And it is like it works sometimes (10%) and mostly (90%) it gives the same error.
I am on the latest version of Docker and I have tried different host's like `Ubuntu 20 LTS`, `WSL`. But this issue now really needs attention, especially because I have now gone to many forums and read the checked old issues, Many people are facing this issue and as of now, I haven't got any idea what is the cause of it.

Here below is the code of my docker-compose.yml file
```
version: "3.7"

services:
  vpn:
    container_name: Nord-VPN
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN             # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=xxxx
      - "PASS=yyyy"            # Required
      - CONNECT=India
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
      - PROTOCOL=UDP
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    networks:
      - primary-net

networks:
  primary-net:

```
