### ISSUE TITLE
Don't get a private key

### ISSUE THREAD

**Issue by jjansen85** [bubuntux/nordvpn#339]
**Describe the bug**
Don't get a private key. Want to change to Nordlynx.

**To Reproduce using docker-compose**
```
version: "3"
services:
  vpn_key:
    image: bubuntux/nordvpn:get_private_key
    container_name: nordvpn_key
    cap_add:
      - NET_ADMIN    
      - NET_RAW
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=xxx
      - PASS=yyy  
```

**Logs**
  
```
A new version of NordVPN is available! Please update the application.
  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
Technology is successfully set to 'NORDLYNX'.

A new version of NordVPN is available! Please update the application.
  
Connecting to Netherlands #924 (nl924.nordvpn.com)
  
You are connected to Netherlands #924 (nl924.nordvpn.com)!

-
  
############################################################
IP: 10.5.0.2/32
Unable to access interface: Protocol not supported
Private Key: 
############################################################
```
