### ISSUE TITLE
torrent WebUI not accessible;

### ISSUE THREAD

**Issue by mpenguin** [bubuntux/nordvpn#345]
**Describe the bug**
I'm running bubuntux/nordvpn in a portainer stack with qbittorrent. I'm essentially running the docker-compose file example but modified for my usage. However, QBitorrent is not accessible on the local network.

I can run qbittorrent in it's own container and have no problems with port 8080. But once I run it through NordVPN, it's no longer accessible on the local network.
I've tested with sabnzbd, and I run access sabnzbd both inside the nordVPN container and on it's own via port 9080. It seems like bubuntux/nordvpn just doesn't trust qbittorrent.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
---
version: '3'


volumes:
  qbittorrent_config:
    external: true

services:

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - USER=XXX
      - PASS=XXX
      - CONNECT=Taiwan
      - TECHNOLOGY=NordLynx
      - NET_LOCAL=192.168.1.0/24
    ports:
      - 8080:8080 #qbittorent
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - qbittorrent_config:/config
      - /mnt/downloads/:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
```

**Expected behavior**
I would expect the stack to create two containers, one for nordvpn and one for qbittorrent. This happens. Both containers appear to launch and are marked as "RUNNING" in Portainer. However, I would also expect QBitorrent to be accessible via port 8080 on the local network. This does not happen.

**Logs**
NordVPN logs show this:
```
Subnet 192.168.1.0/24 is whitelisted successfully.
You are connected to Taiwan #73 (tw73.nordvpn.com)!
```

So it whitelists the local network and connects successfully.

Qbittorrent logs show this:
```
"Web UI: Unable to bind to IP: 192.168.1.100, port: 8080. Reason: The address is not available"
```
That's all it shows.

**Additional context**

I've also tried adding the WEBUI option to the vpn and to the torrent. It makes no difference. I've tried ports 8080, 8090, and 8888. It makes no difference.

I've also tried using NETWORK= instead of NET_LOCAL=. In your docker-compose example, you use NETWORK, but in the environment variables, it lists NET_LOCAL. I've tried both. No change.

I was able to get linuxserver/sabnzbd successfully running and accessible through the vpn on port 9080 without any problems, so this seems limited to qbittorrent for some reason.

Is there anything else I can try to access the QBittorrent webui?
