### ISSUE TITLE
Can't connect to trackers with qbittorrent when running through vpn as a container

### ISSUE THREAD

**Issue by maurocolella** [bubuntux/nordvpn#367]
**Describe the bug**
I have set this up as a vpn gateway container, via docker-compose, also tried the nordlynx version.

In both cases the containers seem to run fine, but I am unable to connect to trackers. I get:
```
Host not found (non-authoritative), try again later 
```

**To Reproduce using docker-compose**

```
version: "3"

services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=<email>     # Required
      - "PASS="         # Required
      #- CONNECT=Switzerland
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.2.0/24  # So it can be accessed within the local network
    ports:
      - 5555:8080
      # qbittorrent
      - 7000:7000
      - 6881:6881
      - 6881:6881/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

Or:

```
version: "3"

services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - NETWORK=192.168.2.0/24  # So it can be accessed within the local network
      - PRIVATE_KEY=<my private key>
    ports:
      - 5555:8080
      # qbittorrent
      - 7000:7000
      - 6881:6881
      - 6881:6881/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
```

And:

```
version: "3"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Europe/London
      - WEBUI_PORT=7000
    volumes:
      - /var/data/qbittorrent/config:/config
      - /.../media/Active:/downloads
    restart: unless-stopped
    network_mode: container:vpn
    #depends_on:
      #- vpn
```

**Expected behavior**
I expect to be able to funnel services through this docker container as a vpn.

**Logs**
```
Unstable connection detected!
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Status: Connected
Current server: hk248.nordvpn.com
Country: Hong Kong
City: Hong Kong
Server IP: 84.17.57.34
Current technology: NORDLYNX
Current protocol: UDP
Transfer: 92 B received, 19.69 KiB sent
Uptime: 5 minutes 20 seconds
Connecting...
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Connecting to Hong Kong #293 (hk293.nordvpn.com)
You are connected to Hong Kong #293 (hk293.nordvpn.com)!
```

**Additional context**
Latest version of portainer, docker-ce and containers, running on Manjaro. Custom firewall config on lan, but traffic from the internet is denied at the router. Custom dns cache/caching server (pi.hole), have disabled both the firewall and dns, and problem persists.

Have tried to explicitly bind qbittorrent to the virtual network interfaces and ips exposed by each technology (wg0, eth0..) to no avail.

I am exposing qbittorrent ports on the vpn's docker compose, which as I understand is necessary with this config, and it works. I can access the qbittorrent web admin, but I can't reach trackers.

Thank you for helping me get through with this. Please.
