### ISSUE TITLE
Configuring portainer

### ISSUE THREAD

**Issue by maurocolella** [bubuntux/nordvpn#37]
Hi,

First of all, thank you for this container. 

Next:

In portainer, I am using `nordvpn` as a stack, along the lines of:

```
version: "2"
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=email@example.com
      - PASS='password'
      - COUNTRY=Japan
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - NETWORK=192.168.2.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=Asia/Manila
    restart: always
```

And that's it. I have a qbittorrent container running, just a regular container, and I presume I should connecting using `--net=service:vpn`

But I just can't figure out how to do that, other than manually starting the qbittorrent container. I'd like to do it through the Web UI offered by portainer as it just is a very convenient long-term way.

Am I.. Missing something?
