### ISSUE TITLE
NordVPN Connects but no containers have internet access

### ISSUE THREAD

**Issue by aneurinprice** [bubuntux/nordvpn#399]
**Describe the bug**
When deploying the VPN container, the container connects to NordVPN successfully, but has no internet access.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    environment: 
      - TOKEN=<redacted>
      - CONNECT=uk1613
      - SERVER=1613
      - TECHNOLOGY=OpenVPN
      - PROTOCOL=UDP
      - NETWORK=10.69.0.0/16
      - DNS=1.1.1.1,8.8.8.8
      - firewall=disabled
    ports:
      - 8080:8080
      - 9117:9117
      - 7878:7878
      - 8989:8989
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    devices:
      - /dev/net/tun
    networks:
      - primary-net
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
    volumes:
      - /srv/torrents:/downloads
      - qbittorrent-config:/config
    network_mode: service:vpn
    depends_on:
      - vpn
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
    volumes:
      - /srv/tv:/tv
      - /srv/torrents:/downloads
      - sonarr-config:/config
    network_mode: service:vpn
    depends_on:
      - vpn
  radarr:
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
    volumes:
      - /srv/movies:/movies
      - /srv/torrents:/downloads
      - radarr-config:/config
    network_mode: service:vpn
    depends_on:
      - vpn
  jackett:
    image: ghcr.io/linuxserver/jackett
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
    volumes:

      - jackett-config:/config
    network_mode: service:vpn
    depends_on:
      - vpn

volumes:
  qbittorrent-config:
  sonarr-config:
  radarr-config:
  jackett-config:

networks:
  primary-net:
```

**Expected behavior**
I would expect the containers in this compose to have some form of internet access.

**Logs**
VPN Container:

```
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:08:30 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
-
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:13:32 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
-
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:18:35 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
-
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:23:37 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:28:39 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
-
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:33:42 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:38:44 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
-
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:43:47 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:48:48 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:53:50 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 14:58:53 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!

-
  
Unstable connection detected!
2023/05/13 15:03:55 neither $XDG_CONFIG_HOME nor $HOME are defined
s6-svc: warning: /var/run/s6/services/nordvpn/notification-fd not present - ignoring request for readiness notification
s6-svlisten1: fatal: unable to subscribe to events for /var/run/s6/services/nordvpn: No such file or directory
Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to United Kingdom #1613 (uk1613.nordvpn.com)

-
\
|
/
-
\
|
/
-
\
|
/
  
You are connected to United Kingdom #1613 (uk1613.nordvpn.com)!
```
```
root@b131269ea0c3:/# nordvpn status
A new version of NordVPN is available! Please update the application.
Status: Connected
Hostname: uk1613.nordvpn.com
IP: 195.206.171.141
Country: United Kingdom
City: London
Current technology: OPENVPN
Current protocol: UDP
Uptime: 1 minute 5 seconds

root@b131269ea0c3:/# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^C
--- 1.1.1.1 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4087ms

root@b131269ea0c3:/# ping 10.69.0.1
PING 10.69.0.1 (10.69.0.1) 56(84) bytes of data.
64 bytes from 10.69.0.1: icmp_seq=1 ttl=63 time=0.164 ms
64 bytes from 10.69.0.1: icmp_seq=2 ttl=63 time=0.282 ms
^C
--- 10.69.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1023ms
rtt min/avg/max/mdev = 0.164/0.223/0.282/0.059 ms

root@b131269ea0c3:/# ip r
default via 172.18.0.1 dev eth0 
10.8.0.0/16 dev nordtun proto kernel scope link src 10.8.0.166 
10.69.0.0/16 via 172.18.0.1 dev eth0 
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.2 
```

**Additional context**
This is running on a Proxmox VM with a flat /16.

Other containers on the host have internet access with no problems.

Running the above stack on my mac also does not work.

```
root@1e48b487d00d:/# nordvpn status
Status: Connected
Hostname: uk1613.nordvpn.com
IP: 195.206.171.141
Country: United Kingdom
City: London
Current technology: OPENVPN
Current protocol: UDP
Transfer: 0 B received, 1.34 KiB sent
Uptime: 45 seconds

root@1e48b487d00d:/# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
--- 1.1.1.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2072ms
```

Any help would be appreciated on this one as I don't quite know what is going on.
