### ISSUE TITLE
Qbittorrent not working through container

### ISSUE THREAD

**Issue by xeon826** [bubuntux/nordvpn#402]
**Describe the bug**
When testing qbittorrent through https://ipleak.net/ the torrent isn't actually detected. Everything gets stuck on "Downloading metadata"

**To Reproduce using docker-compose**
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables


      - TOKEN=(ommitted)    # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
      
# The torrent service would be available at http://localhost:8080/ 
# or anywhere inside of the local network http://192.168.1.xxx:8080
```

- Navigate to localhost:8080
- Open https://ipleak.net/
- Scroll to section where it says "Torrent Address Section"
- Press "Activate" 
- Copy magnet link to qbittorrent
- Navigate back to ipleak, the torrent wasn't event detected

**Expected behavior**
VPN ip should show in the list under "Torrent Address Section" after adding magnet

**Logs**
````
WARNING: Found orphan containers (nordvpn_nordlynx_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting nordvpn_vpn_1 ... done
Starting nordvpn_torrent_1 ... done
Attaching to nordvpn_vpn_1, nordvpn_torrent_1
vpn_1      | [migrations] started
vpn_1      | [migrations] no migrations found
vpn_1      | fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
vpn_1      | usermod: no changes
vpn_1      | ───────────────────────────────────────
vpn_1      |   _____ __ __ _____ _____ _____ _____
vpn_1      |  |     |  |  |   __|_   _|     |     |
vpn_1      |  |   --|  |  |__   | | | |  |  | | | |
vpn_1      |  |_____|_____|_____| |_| |_____|_|_|_|
vpn_1      |        _____ __ __ _ __    ____
vpn_1      |       | __  |  |  | |  |  |    \
vpn_1      |       | __ -|  |  | |  |__|  |  |
vpn_1      |       |_____|_____|_|_____|____/
vpn_1      |
vpn_1      |   Based on images from linuxserver.io
vpn_1      | ───────────────────────────────────────
vpn_1      |
vpn_1      | To support the app dev(s) visit:
vpn_1      | Bubuntux: https://github.com/sponsors/bubuntux
vpn_1      | To support LSIO projects visit:
vpn_1      | https://www.linuxserver.io/donate/
vpn_1      |
vpn_1      | ───────────────────────────────────────
vpn_1      | GID/UID
vpn_1      | ───────────────────────────────────────
vpn_1      |
vpn_1      | User UID:    (ommitted)
vpn_1      | User GID:    (ommitted)
vpn_1      | ───────────────────────────────────────
vpn_1      |
torrent_1  | [migrations] started
torrent_1  | [migrations] no migrations found
vpn_1      | Firewall is up, everything has to go through the vpn
vpn_1      | Enabling connection to secure interface and docker network
vpn_1      | No inet6 network
vpn_1      | Enabling connection to network 192.168.1.0/24
torrent_1  | usermod: no changes
torrent_1  | ───────────────────────────────────────
torrent_1  |
torrent_1  |       ██╗     ███████╗██╗ ██████╗
torrent_1  |       ██║     ██╔════╝██║██╔═══██╗
torrent_1  |       ██║     ███████╗██║██║   ██║
torrent_1  |       ██║     ╚════██║██║██║   ██║
torrent_1  |       ███████╗███████║██║╚██████╔╝
torrent_1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
torrent_1  |
torrent_1  |    Brought to you by linuxserver.io
torrent_1  | ───────────────────────────────────────
torrent_1  |
torrent_1  | To support LSIO projects visit:
torrent_1  | https://www.linuxserver.io/donate/
torrent_1  |
torrent_1  | ───────────────────────────────────────
torrent_1  | GID/UID
torrent_1  | ───────────────────────────────────────
torrent_1  |
torrent_1  | User UID:    (ommitted)
torrent_1  | User GID:    (ommitted)
torrent_1  | ───────────────────────────────────────
torrent_1  |
vpn_1      | [custom-init] No custom files found, skipping...
torrent_1  | [custom-init] No custom files found, skipping...
vpn_1      | [ls.io-init] done.
torrent_1  | WARNING: CPU random generator seem to be failing, disabling hardware random number generation
torrent_1  | WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
torrent_1  | WebUI will be started shortly after internal preparations. Please wait...
torrent_1  | [ls.io-init] done.
A new version of NordVPN is available! Please update the application.
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
A new version of NordVPN is available! Please update the application.
Technology is already set to 'NORDLYNX'.
A new version of NordVPN is available! Please update the application.
Subnet 172.21.0.0/16 is whitelisted successfully.
A new version of NordVPN is available! Please update the application.
Subnet 192.168.1.0/24 is whitelisted successfully.
vpn_1      | Connecting...
A new version of NordVPN is available! Please update the application.
Connecting to United States #9446 (us9446.nordvpn.com)
You are connected to United States #9446 (us9446.nordvpn.com)!
############################################################
vpn_1      | __  .___  ___. .______     ______   .______     .___________.    ___      .__   __. .___________.
vpn_1      | |  | |   \/   | |   _  \   /  __  \  |   _  \    |           |   /   \     |  \ |  | |           |
vpn_1      | |  | |  \  /  | |  |_)  | |  |  |  | |  |_)  |   `---|  |----`  /  ^  \    |   \|  | `---|  |----`
vpn_1      | |  | |  |\/|  | |   ___/  |  |  |  | |      /        |  |      /  /_\  \   |  . `  |     |  |
vpn_1      | |  | |  |  |  | |  |      |  `--'  | |  |\  \----.   |  |     /  _____  \  |  |\   |     |  |
vpn_1      | |__| |__|  |__| | _|       \______/  | _| `._____|   |__|    /__/     \__\ |__| \__|     |__|
vpn_1      | ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
vpn_1      | Please migrate to the NordLynx container (https://github.com/bubuntux/nordlynx)
vpn_1      | Here is your private Key: (ommitted)
vpn_1      | IP: 10.5.0.2/32
vpn_1      | ############################################################
````

**Additional context**
OS: Ubuntu 22.04 jammy
Version of container: v3.12.3
Nordvpn version inside container: 3.16.2

Am I using this correctly? I see the message "Please migrate to the NordLynx container" at the end of the output though I'm not entirely sure what this means, if I'm just wanting to use it for torrenting, shouldn't pulling up the nordvpn container and opening qbittorrent through the web portal be enough or am I missing something?

I want to add this is when I can actually get my ip to show **at all**, it seems it's not even making a connection a lot of the time.

Update: So looking through the advanced settings of the web UI I saw "net work interface" in the Advanced settings and changed it to "nordlynx" it seems to be working after I did this, just to make sure, can anyone confirm this is what I'm supposed to do?
