### ISSUE TITLE
Unable to pull latest NordVPN image?

### ISSUE THREAD

**Issue by sly433** [bubuntux/nordvpn#404]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**
I keep getting this error:
-
  
A new version of NordVPN is available! Please update the application.

-
  

-
  
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Invalid token.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn:latest
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=
      - CONNECT=Switzerland
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8083:8083
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  torrent:
    image: linuxserver/qbittorrent:latest
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - WEBUI_PORT=8089
      - PUID=1026
      - PGID=101
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/docker/downloads:/downloads
    restart: always
```

**Expected behavior**
I would imagine this pulls the latest nordvpn image and should run normally?

**Logs**
-
  
A new version of NordVPN is available! Please update the application.
  
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Invalid token.

**Additional context**
Nordvpn was working a few days back - and now nothing?
