### ISSUE TITLE
Invalid Token error even with fresh token - Synology NAS

### ISSUE THREAD

**Issue by Kelson448** [bubuntux/nordvpn#406]
The latest version of the docker container does not seem to work for me on my synology NAS, even with a freshly generated token. I am receiving an invalid token error 

**Command Used (the tutorial command)**
```
sudo docker run -ti --cap-add=NET_ADMIN --cap-add=NET_RAW --name vpn \
           -e TOKEN=... \
           -e TECHNOLOGY=NordLynx -d ghcr.io/bubuntux/nordvpn
```

**Expected behavior**
This should create a container that runs and connects to NordVPN

**Logs**
```
[0m -    -    [31mIt's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support. 
[0mInvalid token.
```

**Additional context**
Running on a Synology DS923+
Note setting it up directly through the container manager also fails
[this closed bug (389)](https://github.com/bubuntux/nordvpn/issues/389)  has some discussion of others encountering similar errors, and as far as I can tell it hasn't been resolved (but its a closed bug, so I'm creating a new issue so it doesn't get lost.)

**Comment by jcmschwa** [comment]
I think I'm having the same issue. I have not updated my containers in a long time and I am trying to figure out what updates I need to make to my compose file, and I am getting the exact same messages in the logs despite generating a brand new token.

**Comment by jcmschwa** [comment]
I tried wrapping my token in quotes and the log message became: "We couldn't log you in - the access token is not valid. Please check if you've entered the token correctly. If the issue persists, contact our customer support."

**Comment by spencercnorton** [comment]
I am Also having this issue. "

[0mInvalid token.
--
2023/08/12 21:44:49 | stdout | [0m -    -    [31mIt's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.

Generated fresh token. same error.

**Comment by sulantha2006** [comment]
Version 3.16.5, still getting the same error. 

```
vpn_1  | Firewall is up, everything has to go through the vpn
vpn_1  | Enabling connection to secure interface and docker network
vpn_1  | No inet6 network
vpn_1  | [custom-init] No custom files found, skipping...
vpn_1  | [ls.io-init] done.
Whoops! /run/nordvpn/nordvpnd.sock not found.
vpn_1  | Invalid token.
```

**Comment by ImpatientTomato** [comment]
Exact same error.

**Comment by philhawthorne** [comment]
I was able to move to the newer Docker image on my Synology running DSM6. My docker-compose I used is below, hopefully this is helpful.

```yaml
vpn:
    container_name: vpn
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_RAW
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    security_opt:
      - no-new-privileges:true
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=REDACTED
      - CONNECT=NORDVPN_TO_CONNECT_TO
      - TECHNOLOGY=NordLynx
      - GROUPID=0
      - TZ=Europe/London
      - NETWORK=192.168.1.1/24 #Adjust for your local network
      - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
      - NET_LOCAL=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')" 
    ports: 
      - 80:80 #Ports to open
```

Be sure to Install the [Wireguard package](https://github.com/runfalk/synology-wireguard). Thanks to @b-kamphorst and the others in the discussion here: https://github.com/bubuntux/nordlynx/discussions/41
