### ISSUE TITLE
How to block all traffic, as soon as VPN tunnel is down

### ISSUE THREAD

**Issue by pipsen** [bubuntux/nordvpn#420]
**Is your feature request related to a problem? Please describe.**
I have following docker-compose.yml:

```
version: "3"
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: VPN
    cap_add:
      - NET_ADMIN
      - NET_RAW 
    environment:
      - TOKEN=<mytoken>
      - CONNECT=Switzerland
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  myservice:
    image: my/service
    network_mode: "service:nordvpn"
    [....]
    depends_on:
      - nordvpn
```

**Describe the solution you'd like**
With this configuration the "myservice" container uses the network of nordvpn and is behind the VPN tunnel - great.
But I made a manual test, and disconnected the NordVPN tunnel inside of the nordvpn container.

- Actual behaviour: the myservice container is still online with plain internet access of host
- Desired behaviour: as soon as the nordvpn is disconnected, the whole traffic shall be blocked from all depending containers

How can I achieve this? Maybe with PRE_CONNECT and POST_CONNECT? Any suggestions?

**Describe alternatives you've considered**
n/A

**Additional context**
I have seen something quite similar with the nordlynx container:

```
- ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
- "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
- "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
```
