### ISSUE TITLE
Container can't access internet to connect to VPN

### ISSUE THREAD

**Issue by pe1uca** [bubuntux/nordvpn#434]
**Describe the bug**
The container can't connect to nordvpn to login.  

**To Reproduce using docker-compose**
```
test:
    container_name: test
    build: .
    command: tail -F anything
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - 'TOKEN=${VPN_TOKEN}'
      - 'CONNECT=us'
      - TECHNOLOGY=NordLynx
      - NETWORK=172.16.0.0/12;192.168.0.0/16;100.64.0.0/10
    ports:
      - "3128:3128"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
```
`docker compose up -d`
`docker compose logs -f`

**Expected behavior**

**Logs**
```
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
test    | Invalid token.
```

**Additional context**
After commenting this file the container works to connect to the VPN
https://github.com/bubuntux/nordvpn/blob/master/rootfs/etc/cont-init.d/00-firewall
