### ISSUE TITLE
the container keeps restarting. the token should not be the error because is valid.

### ISSUE THREAD

**Issue by CeskoFTB** [bubuntux/nordvpn#436]
**Describe the bug**
Synology NAS
No firewall
the container keeps restarting. the token should not be the error because is valid.

**To Reproduce using docker-compose**

```
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: Bubuntux_Nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    devices:
      - /dev/net/tun
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
       - TOKEN=e************************      # Required
      - CONNECT=CH
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8118:8118                    #
      - 8080:8080                    #
      - 9091:9091                    # Transmission
      - 51413:51413                  # Transmission
      - 51413:51413/udp              # Transmission
      - 5800:5800                    # JDownloader2 unused if headless
      - 5900:5900                    # JDownloader2 unused if headless
      - 3129:3129                    # JDownloader2
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recommended if using ipv4 only
    restart: unless-stopped
  
```

**Logs**

date | stream | content
-- | -- | --
2024/10/23 10:58:15 | stdout | Invalid token.
2024/10/23 10:58:15 | stdout | -     -    It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
2024/10/23 10:58:15 | stdout | -    A new version of NordVPN is available! Please update the application.
2024/10/23 10:58:13 | stdout | [ls.io-init] done.
2024/10/23 10:58:13 | stdout | [custom-init] No custom files found, skipping...
2024/10/23 10:58:13 | stdout | Enabling connection to network 192.168.1.0/24
2024/10/23 10:58:13 | stdout | No inet6 network
2024/10/23 10:58:13 | stdout |  
2024/10/23 10:58:13 | stdout | ───────────────────────────────────────
2024/10/23 10:58:13 | stdout | User GID:    911
2024/10/23 10:58:13 | stdout | User UID:    911
2024/10/23 10:58:13 | stdout |  
2024/10/23 10:58:13 | stdout | ───────────────────────────────────────
2024/10/23 10:58:13 | stdout | GID/UID
2024/10/23 10:58:13 | stdout | ───────────────────────────────────────
2024/10/23 10:58:13 | stdout |  
2024/10/23 10:58:13 | stdout | https://www.linuxserver.io/donate/
2024/10/23 10:58:13 | stdout | To support LSIO projects visit:
2024/10/23 10:58:13 | stdout | Bubuntux: https://github.com/sponsors/bubuntux
2024/10/23 10:58:13 | stdout | To support the app dev(s) visit:
2024/10/23 10:58:13 | stdout |  
2024/10/23 10:58:13 | stdout | ───────────────────────────────────────
2024/10/23 10:58:13 | stdout | Based on images from linuxserver.io
2024/10/23 10:58:13 | stdout |  
2024/10/23 10:58:13 | stdout | \|_____\|_____\|_\|_____\|____/
2024/10/23 10:58:13 | stdout | \| __ -\|  \|  \| \|  \|__\|  \|  \|
2024/10/23 10:58:13 | stdout | \| __  \|  \|  \| \|  \|  \|    \
2024/10/23 10:58:13 | stdout | _____ __ __ _ __    ____
2024/10/23 10:58:13 | stdout | \|_____\|_____\|_____\| \|_\| \|_____\|_\|_\|_\|
2024/10/23 10:58:13 | stdout | \|   --\|  \|  \|__   \| \| \| \|  \|  \| \| \| \|
2024/10/23 10:58:13 | stdout | \|     \|  \|  \|   __\|_   _\|     \|     \|
2024/10/23 10:58:13 | stdout | _____ __ __ _____ _____ _____ _____
2024/10/23 10:58:13 | stdout | ───────────────────────────────────────
2024/10/23 10:58:13 | stdout | usermod: no changes
2024/10/23 10:58:13 | stdout | Enabling connection to secure interface and docker network
2024/10/23 10:58:12 | stdout | Firewall is up, everything has to go through the vpn
2024/10/23 10:58:12 | stderr | fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
2024/10/23 10:58:12 | stdout | [migrations] no migrations found
2024/10/23 10:58:12 | stdout | [migrations] started

**Additional context**
Distribution used, versions, architecture and any other context about the problem here.
