### ISSUE TITLE
Unraid support

### ISSUE THREAD

**Issue by shiftylilbastrd** [bubuntux/nordvpn#55]
Been using this container for quite some time now and I'm really happy with the functionality. Up until now I've been implementing through docker-compose using the code below to route all qbittorrent traffic through the container and to access the webui.

I recently built a new system that is running Unraid and for the life of me I can't get it operational. I've been using Community Apps plugin for access to Docker Hub to pull the container but as my only experience is with using docker-compose I'm not sure how to translate what I was doing to what I need to do now. I can get it installed and a curl request shows I'm connected through the VPN but the log is showing some errors. (https://pastebin.com/82HDWsBu)

The big problem is that I can't seem to figure out how the `--device /dev/net/tun` needs to be added so I can route qBittorrent through it. I've also included a screenshot of the current variables set in Unraid.

Was wondering if you could lend any insight into how to get it working. 
```
    vpn:
        image: bubuntux/nordvpn:latest
        container_name: nordvpn
        cap_add:
            - net_admin
        devices:
            - /dev/net/tun
        restart: always
        environment:
            - USER=${nord_user}
            - PASS=${nord_pass}
            - COUNTRY=United_States
            - PROTOCOL=UDP
            - CATEGORY=P2P
            - NETWORK=192.168.1.0/24,10.0.75.0/24
            - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
            - TZ=${TZ}
        ports:
            - 6881:6881
            - 8113:8113
            - 8112:8112
            - 58846:58846
      qbittorrent:
        image: linuxserver/qbittorrent:latest
        container_name: qbit
        network_mode: service:vpn
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=000
            - WEBUI_PORT=8113
            - VERSION=latest
        volumes:
            - ${cont_dir}/qbittorrent/config:/config
            - ${download_dir}:/downloads
        restart: always
        #depends_on:
            #- vpn
```
![Untitled](https://user-images.githubusercontent.com/39231871/73699148-ee492b00-4697-11ea-93cb-61854f600c96.png)
