### ISSUE TITLE
Local network routing not working in latest update

### ISSUE THREAD

**Issue by mdhiggins** [bubuntux/nordvpn#69]
***IMPORTANT!!! Any Bug without this format would be automatically close. ( before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) )***

**Describe the bug**
Since the 3.7 update I am unable to access other containers that share the nordvpn container as their network via the local IP address internally. Previously would have radarr/sonarr and nzbget all connected and referencing by their local IP address (10.0.1.2) but now that fails. Reverting back to 3.6.1-1 fixes the issue. Additionally I had health checks on these containers that would access via their local IP address to ensure they were available on the local network that are failing (10.0.1.2:6789 not accessible inside radarr)

**To Reproduce using docker CLI**
N/A

**To Reproduce without docker CLI**
```
  nordvpn:
    image: bubuntux/nordvpn:3.6.1-1
    container_name: nordvpn
    network_mode: bridge
    environment:
      - USER=${NORDUSER}
      - PASS=${NORDPASS}
      - NETWORK=10.0.0.0/16
      - TZ=America/New_York
    ports:
      - 6789:6789 # NZBGet
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8112:8112 # Deluge
    devices: 
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: always
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    depends_on:
      - nordvpn
    network_mode: service:nordvpn
    volumes:
      - /opt/appdata/nzbget/config:/config
      - /mnt/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    depends_on:
      - nordvpn
      - nzbget
    network_mode: service:nordvpn
    volumes:
      - /opt/appdata/radarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SMA_UPDATE=true
    restart: always
```

**Logs**
```
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
Subnet 10.0.0.0/16 is whitelisted successfully.
Connecting to United States #4933 (us4933.nordvpn.com)
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 OpenVPN 2.4.8 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 18 2019
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: Connected to management server at /var/run/nordvpn-openvpn.sock
nordvpn          | 2020/03/16 15:57:15 [Error] sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: CMD 'state on'
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: CMD 'username "Auth" FpxczFmT4Cydryow6vLmKXQG'
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: CMD 'password [...]'
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit
We could not disable IPv6. For more information, please check activity log.
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]96.9.245.99:1194
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 UDP link local: (not bound)
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 UDP link remote: [AF_INET]96.9.245.99:1194
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: >STATE:1584388635,WAIT,,,,,,
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 MANAGEMENT: >STATE:1584388635,AUTH,,,,,,
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 TLS: Initial packet from [AF_INET]96.9.245.99:1194, sid=6a989a1f 33ae967f
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 VERIFY KU OK
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 Validating certificate extended key usage
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 VERIFY EKU OK
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 VERIFY OK: depth=0, CN=us4933.nordvpn.com
\2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1634'
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
nordvpn          | 2020/03/16 15:57:15 [INFO] Mon Mar 16 15:57:15 2020 [us4933.nordvpn.com] Peer Connection Initiated with [AF_INET]96.9.245.99:1194
|2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 MANAGEMENT: >STATE:1584388636,GET_CONFIG,,,,,,
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 SENT CONTROL [us4933.nordvpn.com]: 'PUSH_REQUEST' (status=1)
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.0.31 255.255.255.0,peer-id 30,cipher AES-256-GCM'
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: timers and/or timeouts modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: explicit notify parm(s) modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: compression parms modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: --ifconfig/up options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: route options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: route-related options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: peer-id set
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: adjusting link_mtu to 1656
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 OPTIONS IMPORT: data channel crypto options modified
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 TUN/TAP device tun0 opened
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 TUN/TAP TX queue length set to 100
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 MANAGEMENT: >STATE:1584388636,ASSIGN_IP,,10.8.0.31,,,,
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip link set dev tun0 up mtu 1500
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip addr add dev tun0 10.8.0.31/24 broadcast 10.8.0.255
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 96.9.245.99/32 via 172.17.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Initialization Sequence Completed
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 MANAGEMENT: >STATE:1584388636,CONNECTED,SUCCESS,10.8.0.31,96.9.245.99,1194,,
You are connected to United States #4933 (us4933.nordvpn.com)!
2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 TUN/TAP device tun0 opened
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 TUN/TAP TX queue length set to 100
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 MANAGEMENT: >STATE:1584388636,ASSIGN_IP,,10.8.0.31,,,,
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip link set dev tun0 up mtu 1500
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip addr add dev tun0 10.8.0.31/24 broadcast 10.8.0.255
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 96.9.245.99/32 via 172.17.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 Initialization Sequence Completed
nordvpn          | 2020/03/16 15:57:16 [INFO] Mon Mar 16 15:57:16 2020 MANAGEMENT: >STATE:1584388636,CONNECTED,SUCCESS,10.8.0.31,96.9.245.99,1194,,
```

**Additional context**
Works in previous version 3.6.1-1
Can access other containers via 127.0.0.1 from inside the container
Can access web interfaces outside the container on the local network
