### ISSUE TITLE
Subdomain registration via Treafik labels stopped working - service is now timing out

### ISSUE THREAD

**Issue by MacGyver27** [bubuntux/nordvpn#73]
Hi,

This is exactly what I email you about and found the same problem on [Reddit](https://www.reddit.com/r/docker/comments/g31ylj/route_containers_through_vpn_nordvpn/) - it started happening 2 weeks ago. Seems the problem is with your image since fork of your docker image [azinchen/nordvpn](https://github.com/azinchen/nordvpn) is working.

**Describe the bug**
I have been using your docker image for the NordVPN as a GW for some time now but I started having some strange problems I would like to ask for your opinion..

The way I have it set up was all docker containers which wanted to access the Internet via VPN were using your container as a network (via network_mode: container:nordvpn). This still works but I thing got broken and I cannot identify the root cause..

Out of the sudden routing to the service via subdomain registration stopped working.. If such a service is bound with the subdomain (via reverse proxy like traefik) it no longer works. It worked for me for about a year now but yesterday it just no longer gets routed to the service. Nothing has changed.. no upgrades of docker nor your image or changes with the reverse proxy - just started timing out.. so I wonder what could be different now.. if you can spare some time to give me your opinion on this..

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: "3.7"

services:
  nordvpn:
    container_name: nordvpn
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - USER=***
      - PASS=***
      - COUNTRY=Czech_Republic
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.255.0/24
      - TZ=Europe/Prague
    restart: always
```

Then use with some another image the following configuration:
```
    // connecting to the nordvpn container
    network_mode: container:nordvpn
    // using traefik labels to register to the subdomain
    labels:
      - traefik.enable=true
      - traefik.port=52880
      - traefik.frontend.entryPoints=https
      - traefik.frontend.rule=Host:service.example.com
      - traefik.backend=clientXYZ
```

**Expected behavior**
As before be able to access the service on its domain name: `service.example.com` but instead it started timing out as also reddit posts describes.

**Logs**
Enabled DEBUG=on but no logs appeared..

**Additional context**
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

uname -a
Linux caradhras 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

docker -v
Docker version 19.03.8, build afacb8b7f0

docker-compose -v
docker-compose version 1.25.3, build d4d1b42b
```

Since other docker image for nordvpn works with traeifk I expect the problem to be with your image - something must have changed :/ Please let us know what you think, it will be greatly appreachiated! Michal
