### ISSUE TITLE
Docker compose `network_mode: service:vpn` sets containers "NetworkMode": "Default"

### ISSUE THREAD

**Issue by ghoto** [bubuntux/nordvpn#94]
I'm running the examples for docker compose and noticed that `network_mode: service:vpn` seems to be faulty on my setup, and it leads to ip leakage.

My env:
```
pi@blackberrypi:~/pirate-hole $ uname -a
Linux blackberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

pi@blackberrypi:~/pirate-hole $ docker --version
Docker version 18.09.1, build 4c52b90

pi@blackberrypi:~/pirate-hole $ docker-compose --version
docker-compose version 1.21.0, build unknown
```

After running both .yml examples I noticed that using `docker inspect torrent` that the NetworkMode is not set to point the container.

Actual:
```
        "HostConfig": {
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
```

Services work, but they **are not** running behind vpn

this can be verified running this test:

`docker -t -i vpn curl http://ifconfig.me`  -> nordvpn exit point
AND
`docker -t -i torrent curl http://ifconfig.me` -> my isp exit point

-----------
Instead it should be like this (running using docker --net container:vpn)

Expected:
```
        "HostConfig": {
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:d7197da80fbcbbfaa0c5de85a794af980930e25fb00210a7dc896274920ea561",
```

`docker -t -i vpn curl http://ifconfig.me`  -> nordvpn exit point
AND
`docker -t -i torrent curl http://ifconfig.me` -> nordvpn exit point

This doesn't seem to be a problem of this image, though if this happens in other environments, the README should be updated so people don't leak their IPs.

**Comment by frdmn** [comment]
Can you share your exact compose setups so we can try to reproduce the problem?

**Comment by ghoto** [comment]
I'm using the compose configurations of the README with my credentials. 

```
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user@email.com     # Required
      - "PASS=pas$word"         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx

  torrent:
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn

  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:                                                                                   
      - vpn:torrent                                                                          
    depends_on:                                                                              
      - torrent                                                                              
    tmpfs:                                                                                   
      - /run                                                                                 
      - /tmp                                                                                 
      - /var/cache/nginx                                                                     
    ports:                                                                                   
      - 80:80                                                                                
      - 443:443                                                                              
    command: -w "http://torrent:8080/;/" 
    
# The torrent service would be available at http://localhost/ 
```

**Comment by larivierec** [comment]
Just tried to reproduce this, I have a very similar configuration.
I do not have the same behaviour.

I can see the network bridge routing through my container hash.

```
ulimits:
      memlock:
        soft: -1
        hard: -1
```

This and the subnet are pretty much the only differences I have.
The memlock is there because I have a bugged Linux kernel causing the VPN container to crash loop and therefore, torrent stopped working (because of Killswitch).
