### ISSUE TITLE
Unable to access containers through browser

### ISSUE THREAD

**Issue by Zelatrix** [bubuntux/nordvpn#95]
I have a Docker Compose file that starts a number of services, one of which is this VPN container. When I run this Compose file, I cannot access any of my containers via the port in my web browser. If I start the services without the VPN container it works just fine, so I suspect that this is either a bug with the container itself, or in my Docker Compose file. I have checked the YAML syntax for my Compose file and followed to documentation for the container very closely, so my hunch is that there is something wrong with the container but I'm not sure what. 

My Compose file is the following, with credentials redacted:

```
version: "3"
services:
   vpn:
      container_name: nordvpn
      image: bubuntux/nordvpn:latest
      network_mode: bridge
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      devices:
        - /dev/net/tun
      environment:
        - USER=[REDACTED]
        - "PASS=[REDACTED]"
        - CONNECT=United_Kingdom
        - TECHNOLOGY=NordLynx
      ports:
        - "80:80"
        - "8080:8080"
        - "8081:8081"
        - "7878:7878"
        - "8989:8989"
        - "9117:9117"

   qbittorrent:
     container_name: qbittorrent
     image: linuxserver/qbittorrent:latest
     network_mode: service:vpn
     environment:
        - WEBUI_PORT=8081:8081
     depends_on:
        - vpn
     restart: always

   pihole:
      container_name: pihole
      image: pihole/pihole:latest
      restart: always

   radarr:
      container_name: radarr
      image: linuxserver/radarr:latest
      volumes:
         - "/media/pi/Seagate/Radarr:/media/pi/storage"
      restart: always
      depends_on:
         - vpn

   sonarr:
      container_name: sonarr
      image: linuxserver/sonarr:latest
      volumes:
         - "/media/pi/Seagate/Sonarr:/media/pi/storage"
      restart: always
      depends_on:
         - vpn

   jackett:
      container_name: jackett
      image: linuxserver/jackett:latest
      restart: always
      depends_on:
         - vpn

   python_script:
      container_name: python_script
      image: python:3
      volumes:
         - "/media/pi/Seagate/pregs:/media/pi/pregs"
      command: python3 /media/pi/pregs/reddit_bot_linux.py
      restart: on-failure

```
