### ISSUE TITLE
Container never leaves "starting" state

### ISSUE THREAD

**Issue by Zelatrix** [bubuntux/nordvpn#96]
**Describe the bug**
I have created and started a container, and it uses an Nginx web proxy. All the other containers which depend on or are used in the NordVPN entry in the Docker Compose file have the status "running" or "healthy". I cannot access the Nginx container because the NordVPN container remains on "starting". I have made sure to follow the documentation on the GitHub page for using a web proxy. 

**To Reproduce without docker CLI**
```
vpn:
     container_name: nordvpn
     image: bubuntux/nordvpn:latest
     cap_add:
       - NET_ADMIN
       - SYS_MODULE
     devices:
       - /dev/net/tun
     environment:
       - USER=[REDACTED]
       - "PASS=[REDACTED]"
       - CONNECT=United_Kingdom
     ports:
       - "8080:8080"
     restart: on-failure

   nginx:
     container_name: nginx
     image: dperson/nginx:latest
     links:
       - vpn:qbittorrent
     depends_on:
       - qbittorrent
     tmpfs:
       - /run
       - /tmp
       - /var/cache/nginx
     ports:
       - 80:80
       - 443:443
     command: -w "http://qbittorrent:8080/;/"

   qbittorrent:
     container_name: qbittorrent
     image: linuxserver/qbittorrent:latest
     network_mode: service:vpn
     depends_on:
       - vpn
     environment:
       - WEBUI_PORT=8080
     restart: unless-stopped
```

**Expected behavior**
What I expect to happen is that when I visit the Nginx container in my browser, I will see the WebUI for the qBittorrent container. Instead, I get an error from the Nginx container telling me the page is unavailable, 

**Additional context**
The distribution I am using is Raspbian Buster on a Raspberry Pi 4, The architecture is ARMv8. I am also managing my containers using Portainer.

**Comment by gynnantonix** [comment]
Did you try waiting 1 minute and then checking the container's status?  The first healthcheck is delayed for 1 minute, during which time the container will show as "starting"

**Comment by rrileyca** [comment]
Old thread but still open... I think this has to do with the healthcheck interval. My container will come up after 5 minutes. 

You can override the healthcheck time with docker-compose: https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by maxiride** [comment]
> Old thread but still open... I think this has to do with the healthcheck interval. My container will come up after 5 minutes.
> 
> You can override the healthcheck time with docker-compose: https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

I've tried, but I'm not sure that a compose defined health check actually overrides the one in the Dockerfile. I've tried to manually exploit the proposed solution with the following compose with no success. @rrileyca can you provide a minimal working example of your approach?

```yml
healthceck:
  test: ["CMD", "exit 0"]
  start_period: 10s
  timout: 10s
  interval: 1m
```
